// Auto-generated by idl-c.fluid

static const struct FieldDef clXSLTOutputMethod[] = {
   { "Xml", 0x00000000 },
   { "HTML", 0x00000001 },
   { "Text", 0x00000002 },
   { "Auto", 0x00000003 },
   { nullptr, 0 }
};


static const struct MethodEntry clXSLTMethods[] = {
   { AC(-1), (APTR)XSLT_RegisterFunction, "RegisterFunction", 0, 0 },
   { AC(-2), (APTR)XSLT_DeregisterFunction, "DeregisterFunction", 0, 0 },
   { AC(-3), (APTR)XSLT_ResolveIncludes, "ResolveIncludes", 0, 0 },
   { AC::NIL, 0, 0, 0, 0 }
};

static const struct ActionArray clXSLTActions[] = {
   { AC::Activate, XSLT_Activate },
   { AC::Clear, XSLT_Clear },
   { AC::GetKey, XSLT_GetKey },
   { AC::Init, XSLT_Init },
   { AC::Refresh, XSLT_Refresh },
   { AC::Reset, XSLT_Reset },
   { AC::SetKey, XSLT_SetKey },
   { AC::NIL, nullptr }
};

