// Auto-generated by idl-c.tiri

static const struct FieldDef clVectorClipUnits[] = {
   { "Undefined", 0x00000000 },
   { "BoundingBox", 0x00000001 },
   { "Userspace", 0x00000002 },
   { nullptr, 0 }
};

static const struct FieldDef clVectorClipFlags[] = {
   { "ApplyFills", 0x00000001 },
   { "ApplyStrokes", 0x00000002 },
   { nullptr, 0 }
};

static ERR VECTORCLIP_NewPlacement(extVectorClip *Self) {
   new (Self) extVectorClip(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR VECTORCLIP_FreePlacement(extVectorClip *Self) {
   Self->~extVectorClip();
   return ERR::Okay;
}

static const struct ActionArray clVectorClipActions[] = {
   { AC::FreePlacement, VECTORCLIP_FreePlacement },
   { AC::Init, VECTORCLIP_Init },
   { AC::NewChild, VECTORCLIP_NewChild },
   { AC::NewPlacement, VECTORCLIP_NewPlacement },
   { AC::NIL, nullptr }
};

