// Auto-generated by idl-c.tiri

static const struct FieldDef clVectorClipUnits[] = {
   { "Undefined", 0x00000000 },
   { "BoundingBox", 0x00000001 },
   { "Userspace", 0x00000002 },
   { nullptr, 0 }
};

static const struct FieldDef clVectorClipFlags[] = {
   { "ApplyFills", 0x00000001 },
   { "ApplyStrokes", 0x00000002 },
   { nullptr, 0 }
};

static ERR VECTORCLIP_New(extVectorClip *Self) {
   new (Self) extVectorClip(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR VECTORCLIP_Free(extVectorClip *Self) {
   Self->~extVectorClip();
   return ERR::Okay;
}

static const struct ActionArray clVectorClipActions[] = {
   { AC::Free, VECTORCLIP_Free },
   { AC::Init, VECTORCLIP_Init },
   { AC::New, VECTORCLIP_New },
   { AC::NewChild, VECTORCLIP_NewChild },
   { AC::NIL, nullptr }
};

