// Auto-generated by idl-c.tiri

static ERR VECTORELLIPSE_New(extVectorEllipse *Self) {
   new (Self) extVectorEllipse(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR VECTORELLIPSE_Free(extVectorEllipse *Self) {
   Self->~extVectorEllipse();
   return ERR::Okay;
}

static const struct ActionArray clVectorEllipseActions[] = {
   { AC::Free, VECTORELLIPSE_Free },
   { AC::Move, VECTORELLIPSE_Move },
   { AC::MoveToPoint, VECTORELLIPSE_MoveToPoint },
   { AC::New, VECTORELLIPSE_New },
   { AC::NIL, nullptr }
};

