// Auto-generated by idl-c.tiri

static ERR VECTORELLIPSE_NewPlacement(extVectorEllipse *Self) {
   new (Self) extVectorEllipse;
   return ERR::Okay;
}

static ERR VECTORELLIPSE_FreePlacement(extVectorEllipse *Self) {
   Self->~extVectorEllipse();
   return ERR::Okay;
}

static const struct ActionArray clVectorEllipseActions[] = {
   { AC::FreePlacement, VECTORELLIPSE_FreePlacement },
   { AC::Move, VECTORELLIPSE_Move },
   { AC::MoveToPoint, VECTORELLIPSE_MoveToPoint },
   { AC::NewPlacement, VECTORELLIPSE_NewPlacement },
   { AC::NIL, nullptr }
};

