// Auto-generated by idl-c.tiri

static ERR VECTORPOLYGON_NewPlacement(extVectorPolygon *Self) {
   new (Self) extVectorPolygon;
   return ERR::Okay;
}

static ERR VECTORPOLYGON_FreePlacement(extVectorPolygon *Self) {
   Self->~extVectorPolygon();
   return ERR::Okay;
}

static const struct ActionArray clVectorPolygonActions[] = {
   { AC::FreePlacement, VECTORPOLYGON_FreePlacement },
   { AC::Move, VECTORPOLYGON_Move },
   { AC::MoveToPoint, VECTORPOLYGON_MoveToPoint },
   { AC::NewObject, VECTORPOLYGON_NewObject },
   { AC::NewPlacement, VECTORPOLYGON_NewPlacement },
   { AC::Resize, VECTORPOLYGON_Resize },
   { AC::NIL, nullptr }
};

