// Auto-generated by idl-c.tiri

static ERR VECTORPOLYGON_New(extVectorPolygon *Self) {
   new (Self) extVectorPolygon(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR VECTORPOLYGON_Free(extVectorPolygon *Self) {
   Self->~extVectorPolygon();
   return ERR::Okay;
}

static const struct ActionArray clVectorPolygonActions[] = {
   { AC::Free, VECTORPOLYGON_Free },
   { AC::Move, VECTORPOLYGON_Move },
   { AC::MoveToPoint, VECTORPOLYGON_MoveToPoint },
   { AC::New, VECTORPOLYGON_New },
   { AC::Resize, VECTORPOLYGON_Resize },
   { AC::NIL, nullptr }
};

