// Auto-generated by idl-c.tiri

static ERR VECTORRECTANGLE_NewPlacement(extVectorRectangle *Self) {
   new (Self) extVectorRectangle;
   return ERR::Okay;
}

static ERR VECTORRECTANGLE_FreePlacement(extVectorRectangle *Self) {
   Self->~extVectorRectangle();
   return ERR::Okay;
}

static const struct ActionArray clVectorRectangleActions[] = {
   { AC::FreePlacement, VECTORRECTANGLE_FreePlacement },
   { AC::Move, VECTORRECTANGLE_Move },
   { AC::MoveToPoint, VECTORRECTANGLE_MoveToPoint },
   { AC::NewObject, VECTORRECTANGLE_NewObject },
   { AC::NewPlacement, VECTORRECTANGLE_NewPlacement },
   { AC::Resize, VECTORRECTANGLE_Resize },
   { AC::NIL, nullptr }
};

