// Auto-generated by idl-c.tiri

static ERR VECTORRECTANGLE_New(extVectorRectangle *Self) {
   new (Self) extVectorRectangle(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR VECTORRECTANGLE_Free(extVectorRectangle *Self) {
   Self->~extVectorRectangle();
   return ERR::Okay;
}

static const struct ActionArray clVectorRectangleActions[] = {
   { AC::Free, VECTORRECTANGLE_Free },
   { AC::Move, VECTORRECTANGLE_Move },
   { AC::MoveToPoint, VECTORRECTANGLE_MoveToPoint },
   { AC::New, VECTORRECTANGLE_New },
   { AC::Resize, VECTORRECTANGLE_Resize },
   { AC::NIL, nullptr }
};

