// Auto-generated by idl-c.tiri

static ERR VECTORSPIRAL_New(extVectorSpiral *Self) {
   new (Self) extVectorSpiral(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR VECTORSPIRAL_Free(extVectorSpiral *Self) {
   Self->~extVectorSpiral();
   return ERR::Okay;
}

static const struct ActionArray clVectorSpiralActions[] = {
   { AC::Free, VECTORSPIRAL_Free },
   { AC::New, VECTORSPIRAL_New },
   { AC::NIL, nullptr }
};

