// Auto-generated by idl-c.tiri

static ERR VECTORSPIRAL_NewPlacement(extVectorSpiral *Self) {
   new (Self) extVectorSpiral;
   return ERR::Okay;
}

static ERR VECTORSPIRAL_FreePlacement(extVectorSpiral *Self) {
   Self->~extVectorSpiral();
   return ERR::Okay;
}

static const struct ActionArray clVectorSpiralActions[] = {
   { AC::FreePlacement, VECTORSPIRAL_FreePlacement },
   { AC::NewObject, VECTORSPIRAL_NewObject },
   { AC::NewPlacement, VECTORSPIRAL_NewPlacement },
   { AC::NIL, nullptr }
};

