// Auto-generated by idl-c.tiri

static ERR VECTORSHAPE_New(extVectorShape *Self) {
   new (Self) extVectorShape(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR VECTORSHAPE_Free(extVectorShape *Self) {
   Self->~extVectorShape();
   return ERR::Okay;
}

static const struct ActionArray clVectorShapeActions[] = {
   { AC::Free, VECTORSHAPE_Free },
   { AC::New, VECTORSHAPE_New },
   { AC::NIL, nullptr }
};

