// Auto-generated by idl-c.tiri

static ERR VECTORSHAPE_NewPlacement(extVectorShape *Self) {
   new (Self) extVectorShape(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR VECTORSHAPE_FreePlacement(extVectorShape *Self) {
   Self->~extVectorShape();
   return ERR::Okay;
}

static const struct ActionArray clVectorShapeActions[] = {
   { AC::FreePlacement, VECTORSHAPE_FreePlacement },
   { AC::NewPlacement, VECTORSHAPE_NewPlacement },
   { AC::NIL, nullptr }
};

