// Auto-generated by idl-c.tiri

static const struct FieldDef clVectorTextVTXF[] = {
   { "Underline", 0x00000001 },
   { "Overline", 0x00000002 },
   { "LineThrough", 0x00000004 },
   { "Blink", 0x00000008 },
   { "Edit", 0x00000010 },
   { "Editable", 0x00000010 },
   { "AreaSelected", 0x00000020 },
   { "NoSysKeys", 0x00000040 },
   { "Overwrite", 0x00000080 },
   { "Secret", 0x00000100 },
   { "Raster", 0x00000200 },
   { nullptr, 0 }
};

FDEF maDeleteLine[] = { { "Line", FD_INT }, { 0, 0 } };

static const struct MethodEntry clVectorTextMethods[] = {
   { AC(-30), (APTR)VECTORTEXT_DeleteLine, "DeleteLine", maDeleteLine, sizeof(struct vt::DeleteLine) },
   { AC::NIL, 0, 0, 0, 0 }
};

static ERR VECTORTEXT_NewPlacement(extVectorText *Self) {
   new (Self) extVectorText;
   return ERR::Okay;
}

static ERR VECTORTEXT_FreePlacement(extVectorText *Self) {
   Self->~extVectorText();
   return ERR::Okay;
}

static const struct ActionArray clVectorTextActions[] = {
   { AC::FreePlacement, VECTORTEXT_FreePlacement },
   { AC::Init, VECTORTEXT_Init },
   { AC::NewPlacement, VECTORTEXT_NewPlacement },
   { AC::NIL, nullptr }
};
