// Auto-generated by idl-c.tiri

static const struct FieldDef clVectorViewportVOF[] = {
   { "Visible", 0x00000000 },
   { "Hidden", 0x00000001 },
   { "Scroll", 0x00000002 },
   { "Inherit", 0x00000003 },
   { nullptr, 0 }
};

static ERR VECTORVIEWPORT_New(extVectorViewport *Self) {
   new (Self) extVectorViewport(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR VECTORVIEWPORT_Free(extVectorViewport *Self) {
   Self->~extVectorViewport();
   return ERR::Okay;
}

static const struct ActionArray clVectorViewportActions[] = {
   { AC::Clear, VECTORVIEWPORT_Clear },
   { AC::Free, VECTORVIEWPORT_Free },
   { AC::Init, VECTORVIEWPORT_Init },
   { AC::Move, VECTORVIEWPORT_Move },
   { AC::MoveToPoint, VECTORVIEWPORT_MoveToPoint },
   { AC::New, VECTORVIEWPORT_New },
   { AC::Redimension, VECTORVIEWPORT_Redimension },
   { AC::Resize, VECTORVIEWPORT_Resize },
   { AC::NIL, nullptr }
};

