// Auto-generated by idl-c.tiri

static const struct FieldDef clVectorWaveWVT[] = {
   { "Smooth", 0x00000001 },
   { "Triangle", 0x00000002 },
   { "Sawtooth", 0x00000003 },
   { nullptr, 0 }
};

static const struct FieldDef clVectorWaveWVC[] = {
   { "Top", 0x00000001 },
   { "Bottom", 0x00000002 },
   { nullptr, 0 }
};

static const struct FieldDef clVectorWaveWVE[] = {
   { "Linear", 0x00000001 },
   { "Quadratic", 0x00000002 },
   { "Smoothstep", 0x00000003 },
   { "Exponential", 0x00000004 },
   { nullptr, 0 }
};

static ERR VECTORWAVE_NewPlacement(extVectorWave *Self) {
   new (Self) extVectorWave;
   return ERR::Okay;
}

static ERR VECTORWAVE_FreePlacement(extVectorWave *Self) {
   Self->~extVectorWave();
   return ERR::Okay;
}

static const struct ActionArray clVectorWaveActions[] = {
   { AC::FreePlacement, VECTORWAVE_FreePlacement },
   { AC::Move, VECTORWAVE_Move },
   { AC::MoveToPoint, VECTORWAVE_MoveToPoint },
   { AC::NewPlacement, VECTORWAVE_NewPlacement },
   { AC::Resize, VECTORWAVE_Resize },
   { AC::NIL, nullptr }
};

