// Auto-generated by idl-c.tiri

static const struct FieldDef clCompressedStreamFormat[] = {
   { "Gzip", 0x00000001 },
   { "Zlib", 0x00000002 },
   { "Deflate", 0x00000003 },
   { nullptr, 0 }
};

static ERR COMPRESSEDSTREAM_NewPlacement(extCompressedStream *Self) {
   new (Self) extCompressedStream;
   return ERR::Okay;
}

static ERR COMPRESSEDSTREAM_FreePlacement(extCompressedStream *Self) {
   Self->~extCompressedStream();
   return ERR::Okay;
}

static const struct ActionArray clCompressedStreamActions[] = {
   { AC::FreePlacement, COMPRESSEDSTREAM_FreePlacement },
   { AC::Init, COMPRESSEDSTREAM_Init },
   { AC::NewPlacement, COMPRESSEDSTREAM_NewPlacement },
   { AC::Read, COMPRESSEDSTREAM_Read },
   { AC::Reset, COMPRESSEDSTREAM_Reset },
   { AC::Seek, COMPRESSEDSTREAM_Seek },
   { AC::Write, COMPRESSEDSTREAM_Write },
   { AC::NIL, nullptr }
};

