// Auto-generated by idl-c.tiri

static const struct FieldDef clImageFlags[] = {
   { "NoPalette", 0x00000001 },
   { "Scalable", 0x00000002 },
   { "New", 0x00000004 },
   { "Mask", 0x00000008 },
   { "Alpha", 0x00000010 },
   { "Lazy", 0x00000020 },
   { "ForceAlpha32", 0x00000040 },
   { nullptr, 0 }
};

static const struct ActionArray clImageActions[] = {
   { AC::Activate, IMAGE_Activate },
   { AC::Free, IMAGE_Free },
   { AC::Init, IMAGE_Init },
   { AC::NewObject, IMAGE_NewObject },
   { AC::NewPlacement, IMAGE_NewPlacement },
   { AC::Query, IMAGE_Query },
   { AC::Read, IMAGE_Read },
   { AC::Refresh, IMAGE_Refresh },
   { AC::SaveImage, IMAGE_SaveImage },
   { AC::SaveToObject, IMAGE_SaveToObject },
   { AC::Seek, IMAGE_Seek },
   { AC::Write, IMAGE_Write },
   { AC::NIL, nullptr }
};

#undef MOD_IDL
#define MOD_IDL "c.PCF:ALPHA=0x10,FORCE_ALPHA_32=0x40,LAZY=0x20,MASK=0x8,NEW=0x4,NO_PALETTE=0x1,SCALABLE=0x2\n"
