// Auto-generated by idl-c.tiri

static const struct FieldDef clWebSocketServerFlags[] = {
   { "StreamMessages", 0x00000001 },
   { "NoUtf8Check", 0x00000002 },
   { "DisableServerVerify", 0x00000004 },
   { "NoAutoPong", 0x00000008 },
   { "SSL", 0x00000010 },
   { nullptr, 0 }
};

FDEF maBroadcast[] = { { "Data", FDF_SPAN|FD_BYTE }, { "Type", FD_INT }, { "Recipients", FD_RESULT|FD_INT }, { 0, 0 } };
FDEF maDisconnectClient[] = { { "WebSocket", FD_OBJECTPTR }, { "Code", FD_INT }, { "Reason", FD_STR }, { 0, 0 } };

static const struct MethodEntry clWebSocketServerMethods[] = {
   { AC(-1), (APTR)WEBSOCKETSERVER_Broadcast, "Broadcast", maBroadcast, sizeof(struct wsv::Broadcast) },
   { AC(-2), (APTR)WEBSOCKETSERVER_DisconnectClient, "DisconnectClient", maDisconnectClient, sizeof(struct wsv::DisconnectClient) },
   { AC::NIL, 0, 0, 0, 0 }
};

static ERR WEBSOCKETSERVER_New(extWebSocketServer *Self) {
   new (Self) extWebSocketServer(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR WEBSOCKETSERVER_Free(extWebSocketServer *Self) {
   Self->~extWebSocketServer();
   return ERR::Okay;
}

static const struct ActionArray clWebSocketServerActions[] = {
   { AC::Free, WEBSOCKETSERVER_Free },
   { AC::Init, WEBSOCKETSERVER_Init },
   { AC::New, WEBSOCKETSERVER_New },
   { AC::NIL, nullptr }
};
