// Auto-generated by idl-c.tiri

static const struct FieldDef clWebSocketFlags[] = {
   { "StreamMessages", 0x00000001 },
   { "NoUtf8Check", 0x00000002 },
   { "DisableServerVerify", 0x00000004 },
   { "NoAutoPong", 0x00000008 },
   { "SSL", 0x00000010 },
   { nullptr, 0 }
};

static const struct FieldDef clWebSocketState[] = {
   { "Connecting", 0x00000000 },
   { "Open", 0x00000001 },
   { "Closing", 0x00000002 },
   { "Closed", 0x00000003 },
   { nullptr, 0 }
};

FDEF maSend[] = { { "Data", FDF_SPAN|FD_BYTE }, { "Type", FD_INT }, { 0, 0 } };
FDEF maPing[] = { { "Data", FDF_SPAN|FD_BYTE }, { 0, 0 } };
FDEF maClose[] = { { "Code", FD_INT }, { "Reason", FD_STR }, { 0, 0 } };

static const struct MethodEntry clWebSocketMethods[] = {
   { AC(-1), (APTR)WEBSOCKET_Send, "Send", maSend, sizeof(struct wsk::Send) },
   { AC(-2), (APTR)WEBSOCKET_Ping, "Ping", maPing, sizeof(struct wsk::Ping) },
   { AC(-3), (APTR)WEBSOCKET_Close, "Close", maClose, sizeof(struct wsk::Close) },
   { AC::NIL, 0, 0, 0, 0 }
};

static ERR WEBSOCKET_New(extWebSocket *Self) {
   new (Self) extWebSocket(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR WEBSOCKET_Free(extWebSocket *Self) {
   Self->~extWebSocket();
   return ERR::Okay;
}

static const struct ActionArray clWebSocketActions[] = {
   { AC::Activate, WEBSOCKET_Activate },
   { AC::Deactivate, WEBSOCKET_Deactivate },
   { AC::Free, WEBSOCKET_Free },
   { AC::Init, WEBSOCKET_Init },
   { AC::New, WEBSOCKET_New },
   { AC::SetKey, WEBSOCKET_SetKey },
   { AC::NIL, nullptr }
};

#undef MOD_IDL
#define MOD_IDL "s.WSRequest:zsPath,zsQuery,zsHost,zsOrigin,zsProtocols,zsProtocol,zsAddress,zsHeaders\nc.WSC:ABNORMAL=0x3ee,GOING_AWAY=0x3e9,INTERNAL_ERROR=0x3f3,INVALID_PAYLOAD=0x3ef,MANDATORY_EXTENSION=0x3f2,MESSAGE_TOO_BIG=0x3f1,NORMAL=0x3e8,NO_STATUS=0x3ed,POLICY_VIOLATION=0x3f0,PROTOCOL_ERROR=0x3ea,TLS_HANDSHAKE=0x3f7,UNSUPPORTED_DATA=0x3eb\nc.WSF:DISABLE_SERVER_VERIFY=0x4,NO_AUTO_PONG=0x8,NO_UTF8_CHECK=0x2,SSL=0x10,STREAM_MESSAGES=0x1\nc.WSM:BINARY=0x2,TEXT=0x1\nc.WSS:CLOSED=0x3,CLOSING=0x2,CONNECTING=0x0,OPEN=0x1\n"
