// Auto-generated by idl-c.tiri

static const struct FieldDef clClipboardFlags[] = {
   { "DragDrop", 0x00000001 },
   { "Host", 0x00000002 },
   { "HistoryBuffer", 0x00000004 },
   { nullptr, 0 }
};

FDEF maAddFile[] = { { "Datatype", FD_INT }, { "Path", FDF_CPPSTRING }, { "Flags", FD_INT }, { 0, 0 } };
FDEF maAddObjects[] = { { "Datatype", FD_INT }, { "Objects", FD_PTR }, { "Flags", FD_INT }, { 0, 0 } };
FDEF maGetFiles[] = { { "Filter", FD_INT }, { "Index", FD_INT }, { "Datatype", FD_RESULT|FD_INT }, { "Files", FD_RESULT|FDF_VECTOR|FD_MUTABLE|FDF_CPPSTRING }, { "Flags", FD_RESULT|FD_INT }, { 0, 0 } };
FDEF maAddText[] = { { "String", FDF_CPPSTRING }, { 0, 0 } };
FDEF maRemove[] = { { "Datatype", FD_INT }, { 0, 0 } };

static const struct MethodEntry clClipboardMethods[] = {
   { AC(-1), (APTR)CLIPBOARD_AddFile, "AddFile", maAddFile, sizeof(struct clip::AddFile) },
   { AC(-2), (APTR)CLIPBOARD_AddObjects, "AddObjects", maAddObjects, sizeof(struct clip::AddObjects) },
   { AC(-3), (APTR)CLIPBOARD_GetFiles, "GetFiles", maGetFiles, sizeof(struct clip::GetFiles) },
   { AC(-4), (APTR)CLIPBOARD_AddText, "AddText", maAddText, sizeof(struct clip::AddText) },
   { AC(-5), (APTR)CLIPBOARD_Remove, "Remove", maRemove, sizeof(struct clip::Remove) },
   { AC::NIL, 0, 0, 0, 0 }
};

static ERR CLIPBOARD_NewPlacement(objClipboard *Self) {
   new (Self) objClipboard;
   return ERR::Okay;
}

static ERR CLIPBOARD_FreePlacement(objClipboard *Self) {
   Self->~objClipboard();
   return ERR::Okay;
}

static const struct ActionArray clClipboardActions[] = {
   { AC::Clear, CLIPBOARD_Clear },
   { AC::DataFeed, CLIPBOARD_DataFeed },
   { AC::Free, CLIPBOARD_Free },
   { AC::FreePlacement, CLIPBOARD_FreePlacement },
   { AC::Init, CLIPBOARD_Init },
   { AC::NewPlacement, CLIPBOARD_NewPlacement },
   { AC::NIL, nullptr }
};

