// Auto-generated by idl-c.tiri

static ERR LZMASTREAM_NewPlacement(extLZMAStream *Self) {
   new (Self) extLZMAStream(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR LZMASTREAM_FreePlacement(extLZMAStream *Self) {
   Self->~extLZMAStream();
   return ERR::Okay;
}

static const struct ActionArray clLZMAStreamActions[] = {
   { AC::FreePlacement, LZMASTREAM_FreePlacement },
   { AC::Init, LZMASTREAM_Init },
   { AC::NewPlacement, LZMASTREAM_NewPlacement },
   { AC::Read, LZMASTREAM_Read },
   { AC::Reset, LZMASTREAM_Reset },
   { AC::Seek, LZMASTREAM_Seek },
   { AC::Write, LZMASTREAM_Write },
   { AC::NIL, nullptr }
};

