// Auto-generated by idl-c.tiri

static ERR LZMASTREAM_New(extLZMAStream *Self) {
   new (Self) extLZMAStream(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR LZMASTREAM_Free(extLZMAStream *Self) {
   Self->~extLZMAStream();
   return ERR::Okay;
}

static const struct ActionArray clLZMAStreamActions[] = {
   { AC::Free, LZMASTREAM_Free },
   { AC::Init, LZMASTREAM_Init },
   { AC::New, LZMASTREAM_New },
   { AC::Read, LZMASTREAM_Read },
   { AC::Reset, LZMASTREAM_Reset },
   { AC::Seek, LZMASTREAM_Seek },
   { AC::Write, LZMASTREAM_Write },
   { AC::NIL, nullptr }
};

