// Auto-generated by idl-c.tiri

static ERR GRADIENTDIAMOND_New(extGradientDiamond *Self) {
   new (Self) extGradientDiamond(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR GRADIENTDIAMOND_Free(extGradientDiamond *Self) {
   Self->~extGradientDiamond();
   return ERR::Okay;
}

static const struct ActionArray clGradientDiamondActions[] = {
   { AC::Free, GRADIENTDIAMOND_Free },
   { AC::New, GRADIENTDIAMOND_New },
   { AC::NIL, nullptr }
};

