// Auto-generated by idl-c.tiri

static const struct FieldDef clGradientSpreadMethod[] = {
   { "Undefined", 0x00000000 },
   { "Pad", 0x00000001 },
   { "Reflect", 0x00000002 },
   { "Repeat", 0x00000003 },
   { "ReflectX", 0x00000004 },
   { "ReflectY", 0x00000005 },
   { "Clip", 0x00000006 },
   { nullptr, 0 }
};

static const struct FieldDef clGradientUnits[] = {
   { "Undefined", 0x00000000 },
   { "BoundingBox", 0x00000001 },
   { "Userspace", 0x00000002 },
   { nullptr, 0 }
};

static const struct FieldDef clGradientColourSpace[] = {
   { "Inherit", 0x00000000 },
   { "SRGB", 0x00000001 },
   { "LinearRGB", 0x00000002 },
   { nullptr, 0 }
};

static ERR GRADIENT_NewPlacement(extGradient *Self) {
   new (Self) extGradient;
   return ERR::Okay;
}

static ERR GRADIENT_FreePlacement(extGradient *Self) {
   Self->~extGradient();
   return ERR::Okay;
}

static const struct ActionArray clGradientActions[] = {
   { AC::FreePlacement, GRADIENT_FreePlacement },
   { AC::Init, GRADIENT_Init },
   { AC::NewPlacement, GRADIENT_NewPlacement },
   { AC::NIL, nullptr }
};
