// Auto-generated by idl-c.tiri

static ERR GRADIENTGOURAUD_New(extGradientGouraud *Self) {
   new (Self) extGradientGouraud(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR GRADIENTGOURAUD_Free(extGradientGouraud *Self) {
   Self->~extGradientGouraud();
   return ERR::Okay;
}

static const struct ActionArray clGradientGouraudActions[] = {
   { AC::Free, GRADIENTGOURAUD_Free },
   { AC::New, GRADIENTGOURAUD_New },
   { AC::NIL, nullptr }
};

