// Auto-generated by idl-c.tiri

static ERR GRADIENTLINEAR_New(extGradientLinear *Self) {
   new (Self) extGradientLinear(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR GRADIENTLINEAR_Free(extGradientLinear *Self) {
   Self->~extGradientLinear();
   return ERR::Okay;
}

static const struct ActionArray clGradientLinearActions[] = {
   { AC::Free, GRADIENTLINEAR_Free },
   { AC::New, GRADIENTLINEAR_New },
   { AC::NIL, nullptr }
};

