// Auto-generated by idl-c.tiri

static ERR GRADIENTMESH_New(extGradientMesh *Self) {
   new (Self) extGradientMesh(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR GRADIENTMESH_Free(extGradientMesh *Self) {
   Self->~extGradientMesh();
   return ERR::Okay;
}

static const struct ActionArray clGradientMeshActions[] = {
   { AC::Free, GRADIENTMESH_Free },
   { AC::New, GRADIENTMESH_New },
   { AC::NIL, nullptr }
};

