// Auto-generated by idl-c.tiri

static ERR GRADIENTDIFFUSION_New(extGradientDiffusion *Self) {
   new (Self) extGradientDiffusion(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR GRADIENTDIFFUSION_Free(extGradientDiffusion *Self) {
   Self->~extGradientDiffusion();
   return ERR::Okay;
}

static const struct ActionArray clGradientDiffusionActions[] = {
   { AC::Free, GRADIENTDIFFUSION_Free },
   { AC::New, GRADIENTDIFFUSION_New },
   { AC::NIL, nullptr }
};

