// Auto-generated by idl-c.tiri

static ERR GRADIENTDIAMOND_NewPlacement(extGradientDiamond *Self) {
   new (Self) extGradientDiamond(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR GRADIENTDIAMOND_FreePlacement(extGradientDiamond *Self) {
   Self->~extGradientDiamond();
   return ERR::Okay;
}

static const struct ActionArray clGradientDiamondActions[] = {
   { AC::FreePlacement, GRADIENTDIAMOND_FreePlacement },
   { AC::NewPlacement, GRADIENTDIAMOND_NewPlacement },
   { AC::NIL, nullptr }
};

