// Auto-generated by idl-c.tiri

static ERR GRADIENTCONIC_New(extGradientConic *Self) {
   new (Self) extGradientConic(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR GRADIENTCONIC_Free(extGradientConic *Self) {
   Self->~extGradientConic();
   return ERR::Okay;
}

static const struct ActionArray clGradientConicActions[] = {
   { AC::Free, GRADIENTCONIC_Free },
   { AC::New, GRADIENTCONIC_New },
   { AC::NIL, nullptr }
};

