// Auto-generated by idl-c.tiri

static const struct FieldDef clGradientDistalGFALL[] = {
   { "Opaque", 0x00000001 },
   { "Linear", 0x00000002 },
   { "Quadratic", 0x00000003 },
   { "Cubic", 0x00000004 },
   { "Smoothstep", 0x00000005 },
   { "Clear", 0x00000006 },
   { nullptr, 0 }
};

static ERR GRADIENTDISTAL_New(extGradientDistal *Self) {
   new (Self) extGradientDistal(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR GRADIENTDISTAL_Free(extGradientDistal *Self) {
   Self->~extGradientDistal();
   return ERR::Okay;
}

static const struct ActionArray clGradientDistalActions[] = {
   { AC::Free, GRADIENTDISTAL_Free },
   { AC::Init, GRADIENTDISTAL_Init },
   { AC::New, GRADIENTDISTAL_New },
   { AC::NIL, nullptr }
};

