// Auto-generated by idl-c.tiri

static ERR GRADIENTRADIAL_NewPlacement(extGradientRadial *Self) {
   new (Self) extGradientRadial(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR GRADIENTRADIAL_FreePlacement(extGradientRadial *Self) {
   Self->~extGradientRadial();
   return ERR::Okay;
}

static const struct ActionArray clGradientRadialActions[] = {
   { AC::FreePlacement, GRADIENTRADIAL_FreePlacement },
   { AC::NewPlacement, GRADIENTRADIAL_NewPlacement },
   { AC::NIL, nullptr }
};

