// Auto-generated by idl-c.tiri

static ERR GRADIENTMESH_NewPlacement(extGradientMesh *Self) {
   new (Self) extGradientMesh(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR GRADIENTMESH_FreePlacement(extGradientMesh *Self) {
   Self->~extGradientMesh();
   return ERR::Okay;
}

static const struct ActionArray clGradientMeshActions[] = {
   { AC::FreePlacement, GRADIENTMESH_FreePlacement },
   { AC::NewPlacement, GRADIENTMESH_NewPlacement },
   { AC::NIL, nullptr }
};

