// Auto-generated by idl-c.tiri

static ERR GRADIENTCONIC_NewPlacement(extGradientConic *Self) {
   new (Self) extGradientConic(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR GRADIENTCONIC_FreePlacement(extGradientConic *Self) {
   Self->~extGradientConic();
   return ERR::Okay;
}

static const struct ActionArray clGradientConicActions[] = {
   { AC::FreePlacement, GRADIENTCONIC_FreePlacement },
   { AC::NewPlacement, GRADIENTCONIC_NewPlacement },
   { AC::NIL, nullptr }
};

