// Auto-generated by idl-c.tiri

static const struct FieldDef clGradientLinearVGF[] = {
   { "ScaledX1", 0x00000001 },
   { "ScaledY1", 0x00000002 },
   { "ScaledX2", 0x00000004 },
   { "ScaledY2", 0x00000008 },
   { "ScaledCX", 0x00000010 },
   { "ScaledCY", 0x00000020 },
   { "ScaledFX", 0x00000040 },
   { "ScaledFY", 0x00000080 },
   { "ScaledRadius", 0x00000100 },
   { "ScaledFocalRadius", 0x00000200 },
   { "FixedX1", 0x00000400 },
   { "FixedY1", 0x00000800 },
   { "FixedX2", 0x00001000 },
   { "FixedY2", 0x00002000 },
   { "FixedCX", 0x00004000 },
   { "FixedCY", 0x00008000 },
   { "FixedFX", 0x00010000 },
   { "FixedFY", 0x00020000 },
   { "FixedRadius", 0x00040000 },
   { "FixedFocalRadius", 0x00080000 },
   { nullptr, 0 }
};

static ERR GRADIENTLINEAR_NewPlacement(extGradientLinear *Self) {
   new (Self) extGradientLinear;
   return ERR::Okay;
}

static ERR GRADIENTLINEAR_FreePlacement(extGradientLinear *Self) {
   Self->~extGradientLinear();
   return ERR::Okay;
}

static const struct ActionArray clGradientLinearActions[] = {
   { AC::FreePlacement, GRADIENTLINEAR_FreePlacement },
   { AC::NewPlacement, GRADIENTLINEAR_NewPlacement },
   { AC::NIL, nullptr }
};
