// Auto-generated by idl-c.tiri

static ERR GRADIENTDISTAL_NewPlacement(extGradientDistal *Self) {
   new (Self) extGradientDistal;
   return ERR::Okay;
}

static ERR GRADIENTDISTAL_FreePlacement(extGradientDistal *Self) {
   Self->~extGradientDistal();
   return ERR::Okay;
}

static const struct ActionArray clGradientDistalActions[] = {
   { AC::FreePlacement, GRADIENTDISTAL_FreePlacement },
   { AC::Init, GRADIENTDISTAL_Init },
   { AC::NewPlacement, GRADIENTDISTAL_NewPlacement },
   { AC::NIL, nullptr }
};

