// Auto-generated by idl-c.tiri

static ERR GRADIENTGOURAUD_NewPlacement(extGradientGouraud *Self) {
   new (Self) extGradientGouraud(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR GRADIENTGOURAUD_FreePlacement(extGradientGouraud *Self) {
   Self->~extGradientGouraud();
   return ERR::Okay;
}

static const struct ActionArray clGradientGouraudActions[] = {
   { AC::FreePlacement, GRADIENTGOURAUD_FreePlacement },
   { AC::NewPlacement, GRADIENTGOURAUD_NewPlacement },
   { AC::NIL, nullptr }
};

