// Auto-generated by idl-c.tiri

static const struct FieldDef clGradientVoronoiWLF[] = {
   { "F1", 0x00000000 },
   { "F2F1", 0x00000001 },
   { "F2", 0x00000002 },
   { "Weighted", 0x00000003 },
   { "Peaks", 0x00000004 },
   { nullptr, 0 }
};

static const struct FieldDef clGradientVoronoiWLM[] = {
   { "Euclidean", 0x00000000 },
   { "Manhattan", 0x00000001 },
   { "Chebyshev", 0x00000002 },
   { nullptr, 0 }
};

static ERR GRADIENTVORONOI_New(extGradientVoronoi *Self) {
   new (Self) extGradientVoronoi(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR GRADIENTVORONOI_Free(extGradientVoronoi *Self) {
   Self->~extGradientVoronoi();
   return ERR::Okay;
}

static const struct ActionArray clGradientVoronoiActions[] = {
   { AC::Free, GRADIENTVORONOI_Free },
   { AC::Init, GRADIENTVORONOI_Init },
   { AC::New, GRADIENTVORONOI_New },
   { AC::NIL, nullptr }
};

