// Auto-generated by idl-c.tiri

static ERR GRADIENTCONTOUR_New(extGradientContour *Self) {
   new (Self) extGradientContour(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR GRADIENTCONTOUR_Free(extGradientContour *Self) {
   Self->~extGradientContour();
   return ERR::Okay;
}

static const struct ActionArray clGradientContourActions[] = {
   { AC::Free, GRADIENTCONTOUR_Free },
   { AC::Init, GRADIENTCONTOUR_Init },
   { AC::New, GRADIENTCONTOUR_New },
   { AC::NIL, nullptr }
};

