// Auto-generated by idl-c.tiri

static const struct FieldDef clGradientDistalGFALL[] = {
   { "None", 0x00000001 },
   { "Linear", 0x00000002 },
   { "Quadratic", 0x00000003 },
   { "Cubic", 0x00000004 },
   { "Smoothstep", 0x00000005 },
   { nullptr, 0 }
};

static ERR GRADIENTDISTAL_NewPlacement(extGradientDistal *Self) {
   new (Self) extGradientDistal;
   return ERR::Okay;
}

static ERR GRADIENTDISTAL_FreePlacement(extGradientDistal *Self) {
   Self->~extGradientDistal();
   return ERR::Okay;
}

static const struct ActionArray clGradientDistalActions[] = {
   { AC::FreePlacement, GRADIENTDISTAL_FreePlacement },
   { AC::Init, GRADIENTDISTAL_Init },
   { AC::NewPlacement, GRADIENTDISTAL_NewPlacement },
   { AC::NIL, nullptr }
};
