// Auto-generated by idl-c.tiri

static ERR GRADIENTRADIAL_New(extGradientRadial *Self) {
   new (Self) extGradientRadial(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR GRADIENTRADIAL_Free(extGradientRadial *Self) {
   Self->~extGradientRadial();
   return ERR::Okay;
}

static const struct ActionArray clGradientRadialActions[] = {
   { AC::Free, GRADIENTRADIAL_Free },
   { AC::New, GRADIENTRADIAL_New },
   { AC::NIL, nullptr }
};

