// Auto-generated by idl-c.tiri

static ERR GRADIENTCONTOUR_NewPlacement(extGradientContour *Self) {
   new (Self) extGradientContour;
   return ERR::Okay;
}

static ERR GRADIENTCONTOUR_FreePlacement(extGradientContour *Self) {
   Self->~extGradientContour();
   return ERR::Okay;
}

static const struct ActionArray clGradientContourActions[] = {
   { AC::FreePlacement, GRADIENTCONTOUR_FreePlacement },
   { AC::Init, GRADIENTCONTOUR_Init },
   { AC::NewPlacement, GRADIENTCONTOUR_NewPlacement },
   { AC::NIL, nullptr }
};

