// Auto-generated by idl-c.tiri

static ERR GRADIENTLINEAR_NewPlacement(extGradientLinear *Self) {
   new (Self) extGradientLinear;
   return ERR::Okay;
}

static ERR GRADIENTLINEAR_FreePlacement(extGradientLinear *Self) {
   Self->~extGradientLinear();
   return ERR::Okay;
}

static const struct ActionArray clGradientLinearActions[] = {
   { AC::FreePlacement, GRADIENTLINEAR_FreePlacement },
   { AC::NewPlacement, GRADIENTLINEAR_NewPlacement },
   { AC::NIL, nullptr }
};

