// Auto-generated by idl-c.tiri

static const struct FieldDef clVectorImageUnits[] = {
   { "Undefined", 0x00000000 },
   { "BoundingBox", 0x00000001 },
   { "Userspace", 0x00000002 },
   { nullptr, 0 }
};

static const struct FieldDef clVectorImageSpreadMethod[] = {
   { "Undefined", 0x00000000 },
   { "Pad", 0x00000001 },
   { "Reflect", 0x00000002 },
   { "Repeat", 0x00000003 },
   { "ReflectX", 0x00000004 },
   { "ReflectY", 0x00000005 },
   { "Clip", 0x00000006 },
   { nullptr, 0 }
};

static const struct FieldDef clVectorImageAspectRatio[] = {
   { "XMin", 0x00000001 },
   { "XMid", 0x00000002 },
   { "XMax", 0x00000004 },
   { "YMin", 0x00000008 },
   { "YMid", 0x00000010 },
   { "YMax", 0x00000020 },
   { "Meet", 0x00000040 },
   { "Slice", 0x00000080 },
   { "None", 0x00000100 },
   { nullptr, 0 }
};

static ERR VECTORIMAGE_New(extVectorImage *Self) {
   new (Self) extVectorImage(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR VECTORIMAGE_Free(extVectorImage *Self) {
   Self->~extVectorImage();
   return ERR::Okay;
}

static const struct ActionArray clVectorImageActions[] = {
   { AC::Free, VECTORIMAGE_Free },
   { AC::Init, VECTORIMAGE_Init },
   { AC::New, VECTORIMAGE_New },
   { AC::NIL, nullptr }
};

