// Auto-generated by idl-c.tiri

static const struct FieldDef clVectorPatternSpreadMethod[] = {
   { "Undefined", 0x00000000 },
   { "Pad", 0x00000001 },
   { "Reflect", 0x00000002 },
   { "Repeat", 0x00000003 },
   { "ReflectX", 0x00000004 },
   { "ReflectY", 0x00000005 },
   { "Clip", 0x00000006 },
   { nullptr, 0 }
};

static const struct FieldDef clVectorPatternUnits[] = {
   { "Undefined", 0x00000000 },
   { "BoundingBox", 0x00000001 },
   { "Userspace", 0x00000002 },
   { nullptr, 0 }
};

static const struct FieldDef clVectorPatternContentUnits[] = {
   { "Undefined", 0x00000000 },
   { "BoundingBox", 0x00000001 },
   { "Userspace", 0x00000002 },
   { nullptr, 0 }
};

static ERR VECTORPATTERN_NewPlacement(extVectorPattern *Self) {
   new (Self) extVectorPattern;
   return ERR::Okay;
}

static ERR VECTORPATTERN_FreePlacement(extVectorPattern *Self) {
   Self->~extVectorPattern();
   return ERR::Okay;
}

static const struct ActionArray clVectorPatternActions[] = {
   { AC::Draw, VECTORPATTERN_Draw },
   { AC::FreePlacement, VECTORPATTERN_FreePlacement },
   { AC::Init, VECTORPATTERN_Init },
   { AC::NewPlacement, VECTORPATTERN_NewPlacement },
   { AC::NIL, nullptr }
};

