// Auto-generated by idl-c.tiri

static const struct FieldDef clXMLFlags[] = {
   { "WellFormed", 0x00000001 },
   { "IncludeComments", 0x00000002 },
   { "StripContent", 0x00000004 },
   { "Indent", 0x00000008 },
   { "Readable", 0x00000008 },
   { "LockRemove", 0x00000010 },
   { "StripHeaders", 0x00000020 },
   { "New", 0x00000040 },
   { "NoEscape", 0x00000080 },
   { "IncludeWhitespace", 0x00000100 },
   { "ParseHTML", 0x00000200 },
   { "StripCDATA", 0x00000400 },
   { "LogAll", 0x00000800 },
   { "ParseEntity", 0x00001000 },
   { "OmitTags", 0x00002000 },
   { "NamespaceAware", 0x00004000 },
   { "HasSchema", 0x00008000 },
   { "Standalone", 0x00010000 },
   { "ReadOnly", 0x00020000 },
   { "IncludeSiblings", (int)0x80000000 },
   { nullptr, 0 }
};

FDEF maSetAttrib[] = { { "Index", FD_INT }, { "Attrib", FD_INT }, { "Name", FDF_CPPSTRING }, { "Value", FDF_CPPSTRING }, { 0, 0 } };
FDEF maSerialise[] = { { "Index", FD_INT }, { "Flags", FD_INT }, { "Result", FD_RESULT|FD_MUTABLE|FDF_CPPSTRING }, { 0, 0 } };
FDEF maInsertXML[] = { { "Index", FD_INT }, { "Where", FD_INT }, { "XML", FDF_CPPSTRING }, { "Result", FD_RESULT|FD_INT }, { 0, 0 } };
FDEF maGetContent[] = { { "Index", FD_INT }, { "Buffer", FD_RESULT|FD_MUTABLE|FDF_CPPSTRING }, { 0, 0 } };
FDEF maSort[] = { { "XPath", FDF_CPPSTRING }, { "Sort", FDF_CPPSTRING }, { "Flags", FD_INT }, { 0, 0 } };
FDEF maRemoveTag[] = { { "Index", FD_INT }, { "Total", FD_INT }, { 0, 0 } };
FDEF maMoveTags[] = { { "Index", FD_INT }, { "Total", FD_INT }, { "DestIndex", FD_INT }, { "Where", FD_INT }, { 0, 0 } };
FDEF maGetAttrib[] = { { "Index", FD_INT }, { "Attrib", FDF_CPPSTRING }, { "Value", FD_RESULT|FD_MUTABLE|FDF_CPPSTRING }, { 0, 0 } };
FDEF maInsertXPath[] = { { "XPath", FDF_CPPSTRING }, { "Where", FD_INT }, { "XML", FDF_CPPSTRING }, { "Result", FD_RESULT|FD_INT }, { 0, 0 } };
FDEF maSearch[] = { { "Expression", FDF_CPPSTRING }, { "Callback", FD_FUNCTIONPTR }, { "Result", FD_RESULT|FD_INT }, { 0, 0 } };
FDEF maFilter[] = { { "XPath", FDF_CPPSTRING }, { 0, 0 } };
FDEF maEvaluate[] = { { "Statement", FDF_CPPSTRING }, { "Result", FD_RESULT|FD_MUTABLE|FDF_CPPSTRING }, { 0, 0 } };
FDEF maInsertContent[] = { { "Index", FD_INT }, { "Where", FD_INT }, { "Content", FDF_CPPSTRING }, { "Result", FD_RESULT|FD_INT }, { 0, 0 } };
FDEF maRemoveXPath[] = { { "XPath", FDF_CPPSTRING }, { "Limit", FD_INT }, { 0, 0 } };
FDEF maGetTag[] = { { "Index", FD_INT }, { "XTag:Result", FD_RESULT|FD_PTR|FD_STRUCT }, { 0, 0 } };
FDEF maRegisterNamespace[] = { { "URI", FDF_CPPSTRING }, { "Result", FD_RESULT|FD_INT|FD_UNSIGNED }, { 0, 0 } };
FDEF maGetNamespaceURI[] = { { "NamespaceID", FD_INT|FD_UNSIGNED }, { "Result", FD_RESULT|FD_MUTABLE|FDF_CPPSTRING }, { 0, 0 } };
FDEF maSetTagNamespace[] = { { "TagID", FD_INT }, { "NamespaceID", FD_INT }, { 0, 0 } };
FDEF maResolvePrefix[] = { { "Prefix", FDF_CPPSTRING }, { "TagID", FD_INT }, { "Result", FD_RESULT|FD_INT|FD_UNSIGNED }, { 0, 0 } };
FDEF maGetEntity[] = { { "Name", FDF_CPPSTRING }, { "Value", FD_RESULT|FD_MUTABLE|FDF_CPPSTRING }, { 0, 0 } };
FDEF maGetNotation[] = { { "Name", FDF_CPPSTRING }, { "Value", FD_RESULT|FD_MUTABLE|FDF_CPPSTRING }, { 0, 0 } };
FDEF maLoadSchema[] = { { "Path", FDF_CPPSTRING }, { 0, 0 } };

static const struct MethodEntry clXMLMethods[] = {
   { AC(-1), (APTR)XML_SetAttrib, "SetAttrib", maSetAttrib, sizeof(struct xml::SetAttrib) },
   { AC(-2), (APTR)XML_Serialise, "Serialise", maSerialise, sizeof(struct xml::Serialise) },
   { AC(-3), (APTR)XML_InsertXML, "InsertXML", maInsertXML, sizeof(struct xml::InsertXML) },
   { AC(-4), (APTR)XML_GetContent, "GetContent", maGetContent, sizeof(struct xml::GetContent) },
   { AC(-5), (APTR)XML_Sort, "Sort", maSort, sizeof(struct xml::Sort) },
   { AC(-6), (APTR)XML_RemoveTag, "RemoveTag", maRemoveTag, sizeof(struct xml::RemoveTag) },
   { AC(-7), (APTR)XML_MoveTags, "MoveTags", maMoveTags, sizeof(struct xml::MoveTags) },
   { AC(-8), (APTR)XML_GetAttrib, "GetAttrib", maGetAttrib, sizeof(struct xml::GetAttrib) },
   { AC(-9), (APTR)XML_InsertXPath, "InsertXPath", maInsertXPath, sizeof(struct xml::InsertXPath) },
   { AC(-10), (APTR)XML_Search, "Search", maSearch, sizeof(struct xml::Search) },
   { AC(-11), (APTR)XML_Filter, "Filter", maFilter, sizeof(struct xml::Filter) },
   { AC(-12), (APTR)XML_Evaluate, "Evaluate", maEvaluate, sizeof(struct xml::Evaluate) },
   { AC(-13), (APTR)XML_ValidateDocument, "ValidateDocument", 0, 0 },
   { AC(-14), (APTR)XML_InsertContent, "InsertContent", maInsertContent, sizeof(struct xml::InsertContent) },
   { AC(-15), (APTR)XML_RemoveXPath, "RemoveXPath", maRemoveXPath, sizeof(struct xml::RemoveXPath) },
   { AC(-16), (APTR)XML_GetTag, "GetTag", maGetTag, sizeof(struct xml::GetTag) },
   { AC(-17), (APTR)XML_RegisterNamespace, "RegisterNamespace", maRegisterNamespace, sizeof(struct xml::RegisterNamespace) },
   { AC(-18), (APTR)XML_GetNamespaceURI, "GetNamespaceURI", maGetNamespaceURI, sizeof(struct xml::GetNamespaceURI) },
   { AC(-19), (APTR)XML_SetTagNamespace, "SetTagNamespace", maSetTagNamespace, sizeof(struct xml::SetTagNamespace) },
   { AC(-20), (APTR)XML_ResolvePrefix, "ResolvePrefix", maResolvePrefix, sizeof(struct xml::ResolvePrefix) },
   { AC(-21), (APTR)XML_GetEntity, "GetEntity", maGetEntity, sizeof(struct xml::GetEntity) },
   { AC(-22), (APTR)XML_GetNotation, "GetNotation", maGetNotation, sizeof(struct xml::GetNotation) },
   { AC(-23), (APTR)XML_LoadSchema, "LoadSchema", maLoadSchema, sizeof(struct xml::LoadSchema) },
   { AC::NIL, 0, 0, 0, 0 }
};

static ERR XML_New(extXML *Self) {
   new (Self) extXML(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR XML_Free(extXML *Self) {
   Self->~extXML();
   return ERR::Okay;
}

static const struct ActionArray clXMLActions[] = {
   { AC::Clear, XML_Clear },
   { AC::DataFeed, XML_DataFeed },
   { AC::Free, XML_Free },
   { AC::Init, XML_Init },
   { AC::New, XML_New },
   { AC::Reset, XML_Reset },
   { AC::SaveToObject, XML_SaveToObject },
   { AC::SetKey, XML_SetKey },
   { AC::NIL, nullptr }
};

