// Auto-generated by idl-c.tiri

namespace rx {
extern ERR Compile(const std::string_view & Pattern, REGEX Flags, std::string * ErrorMsg, struct Regex ** Result);
extern ERR Search(struct Regex * Regex, const std::string_view & Text, RMATCH Flags, FUNCTION * Callback);
extern ERR Replace(struct Regex * Regex, const std::string_view & Text, const std::string_view & Replacement, std::string * Output, RMATCH Flags);
extern ERR Split(struct Regex * Regex, const std::string_view & Text, kt::vector<std::string> * Output, RMATCH Flags);
extern ERR GetCaptureIndex(struct Regex * Regex, const std::string_view & Name, kt::vector<int> * Indices);

} // namespace
#ifndef FDEF
#define FDEF static const struct FunctionField
#endif

FDEF argsCompile[] = { { "Error", FD_INT|FD_ERROR }, { "Pattern", FDF_CPPSTRING }, { "Flags", FD_INT }, { "ErrorMsg", FD_RESULT|FD_MUTABLE|FDF_CPPSTRING }, { "Regex:Result", FD_RESULT|FD_PTR|FD_STRUCT|FD_ALLOC }, { 0, 0 } };
FDEF argsGetCaptureIndex[] = { { "Error", FD_INT|FD_ERROR }, { "Regex:Regex", FD_PTR|FD_STRUCT }, { "Name", FDF_CPPSTRING }, { "Indices", FD_RESULT|FDF_VECTOR|FD_MUTABLE|FD_INT }, { 0, 0 } };
FDEF argsReplace[] = { { "Error", FD_INT|FD_ERROR }, { "Regex:Regex", FD_PTR|FD_STRUCT }, { "Text", FDF_CPPSTRING }, { "Replacement", FDF_CPPSTRING }, { "Output", FD_RESULT|FD_MUTABLE|FDF_CPPSTRING }, { "Flags", FD_INT }, { 0, 0 } };
FDEF argsSearch[] = { { "Error", FD_INT|FD_ERROR }, { "Regex:Regex", FD_PTR|FD_STRUCT }, { "Text", FDF_CPPSTRING }, { "Flags", FD_INT }, { "Callback", FD_FUNCTIONPTR }, { 0, 0 } };
FDEF argsSplit[] = { { "Error", FD_INT|FD_ERROR }, { "Regex:Regex", FD_PTR|FD_STRUCT }, { "Text", FDF_CPPSTRING }, { "Output", FD_RESULT|FDF_VECTOR|FD_MUTABLE|FDF_CPPSTRING }, { "Flags", FD_INT }, { 0, 0 } };

const struct Function glFunctions[] = {
   { (APTR)rx::Compile, "Compile", argsCompile },
   { (APTR)rx::Search, "Search", argsSearch },
   { (APTR)rx::Replace, "Replace", argsReplace },
   { (APTR)rx::Split, "Split", argsSplit },
   { (APTR)rx::GetCaptureIndex, "GetCaptureIndex", argsGetCaptureIndex },
   { nullptr, nullptr, nullptr }
};

#undef MOD_IDL
#define MOD_IDL "s.Regex:zsPattern,lFlags\nc.REGEX:DOT_ALL=0x4,ICASE=0x1,MULTILINE=0x2\nc.RMATCH:CONTINUOUS=0x20,NOT_BEGIN_OF_LINE=0x1,NOT_BEGIN_OF_WORD=0x4,NOT_END_OF_LINE=0x2,NOT_END_OF_WORD=0x8,NOT_NULL=0x10,PREV_AVAILABLE=0x40,REPLACE_FIRST_ONLY=0x100,REPLACE_NO_COPY=0x80,WHOLE=0x200\n"
