#pragma once
#define KOTUKU_MAIN_H TRUE

#ifndef PLATFORM_CONFIG_H
#include <kotuku/config.h> // Generated by cmake
#endif

#ifdef _MSC_VER
#pragma warning (disable : 4244 4311 4312 4267 4244 4068) // Disable annoying VC++ typecast warnings

#define strncasecmp _strnicmp
#define strcasecmp _stricmp
#endif

#ifdef __GNUC__
#define PACK(D) D __attribute__((__packed__))
#endif

#ifdef _MSC_VER
#define PACK(D) __pragma(pack(push, 1)) D __pragma(pack(pop))
#endif

#include <kotuku/system/types.h>
#include <kotuku/vector.hpp>
#include <kotuku/system/registry.h>
#include <kotuku/system/errors.h>
#include <kotuku/system/fields.h>
#include <kotuku/modules/core.h>

#include <type_traits>
#include <memory>
#include <optional>
#include <concepts>

inline constexpr int64_t TAGEND = 0;

namespace kt {

//********************************************************************************************************************

// Concept for types that support lock(timeout)/unlock() interface
template<typename T>
concept Lockable = requires(T obj, int timeout) {
   { obj.lock(timeout) } -> std::same_as<ERR>;
   { obj.unlock() } -> std::same_as<void>;
};

// Concept for Kotuku object types (either derived from Object or implementing Lockable interface)
template<typename T>
concept KotukuObject = std::is_base_of_v<Object, T> or Lockable<T>;

// Concept for arithmetic types (integral or floating point)
template<typename T>
concept Numeric = std::is_arithmetic_v<T>;

// Concept for numeric types (arithmetic or enum)
template<typename T>
concept NumericOrEnum = std::is_arithmetic_v<T> or std::is_enum_v<T>;

// Concept for numeric or SCALE-derived types (for dimension fields)
template<typename T>
concept NumericOrScale = std::is_arithmetic_v<T> or std::is_base_of_v<SCALE, T>;

// Concept for counter types used in reference counting
template<typename C>
concept RefCounter = (std::is_arithmetic_v<C> or std::is_same_v<C, std::atomic_int>);

// Concept for invocable cleanup functions
template<typename F>
concept Invocable = std::is_invocable_v<std::decay_t<F>>;

//********************************************************************************************************************

template <class T = double> struct POINT {
   T x, y;

   constexpr POINT<T> & operator += (const POINT &Other) {
      x += Other.x;
      y += Other.y;
      return *this;
   }

   [[nodiscard]] constexpr bool operator==(const POINT &) const = default;
};

// Fast distance approximation for integral types
template <std::integral T>
[[nodiscard]] T operator-(const POINT<T> A, const POINT<T> &B) {
   if (A == B) return T{0};
   double a = std::abs(double(B.x - A.x));
   double b = std::abs(double(B.y - A.y));
   if (a > b) std::swap(a, b);
   return T(b + 0.428 * a * a / b); // Error level of ~1.04%
}

// Optimized distance calculation for floating-point types
template <std::floating_point T>
[[nodiscard]] T operator-(const POINT<T> A, const POINT<T> &B) {
   if (A == B) return T{0};
   T a = std::abs(B.x - A.x);
   T b = std::abs(B.y - A.y);
   if (a > b) std::swap(a, b);
   return b + T(0.428) * a * a / b; // Direct T arithmetic
}

template <class T = double, class M = double>
   requires (std::is_arithmetic_v<T> and std::is_arithmetic_v<M>)
[[nodiscard]] POINT<T> operator * (const POINT<T> &lhs, const M &Multiplier) {
   return POINT<T> { T(lhs.x * Multiplier), T(lhs.y * Multiplier) };
}

//********************************************************************************************************************

DEFINE_ENUM_FLAG_OPERATORS(ERR)

//********************************************************************************************************************
// Defer() function for calling lambdas at end-of-scope.
// Example: auto cleanup = kt::Defer([&]() { log.msg("Finished"); });

template <typename FUNC> struct deferred_call {
   deferred_call(const deferred_call &that) = delete;
   deferred_call & operator = (const deferred_call &that) = delete;
   deferred_call(deferred_call &&that) = delete;
   deferred_call(FUNC &&f) : func(std::forward<FUNC>(f)) { }

   ~deferred_call() { func(); }

private:
   FUNC func;
};

template <Invocable F>
[[nodiscard]] deferred_call<std::decay_t<F>> Defer(F &&f) {
   return deferred_call<std::decay_t<F>>(std::forward<F>(f));
}

//********************************************************************************************************************
// Deleter for use with std::unique_ptr to free objects correctly on destruction.  Note that these always assume that
// the object pointer remains safe (cannot be deleted by external factors).
//
// E.g. std::unique_ptr<objVectorViewport, DeleteObject<objVectorViewport>> viewport;

template <class T = Object> struct DeleteObject {
  void operator()(T *Object) const { if (Object) FreeResource(Object->UID); }
};

// Simplify the creation of unique pointers with the destructor

template <class T = Object> requires std::is_base_of_v<Object, T>
[[nodiscard]] std::unique_ptr<T, DeleteObject<T>> make_unique_object(T *Object) {
   return std::unique_ptr<T, DeleteObject<T>>(Object, DeleteObject<T>{});
}

// Variant for std::shared_ptr

template <class T = Object> requires std::is_base_of_v<Object, T>
[[nodiscard]] std::shared_ptr<T> make_shared_object(T *Object) {
   return std::shared_ptr<T>(Object, DeleteObject<T>{});
}

//********************************************************************************************************************
// Scoped object locker.  Use granted() to confirm that the lock has been granted.
// Uses the KotukuObject concept to ensure T is either Object-derived or has lock()/unlock() methods.

template <KotukuObject T = Object>
class ScopedObjectLock {
   private:
      bool quicklock = false;

   public:
      ERR error = ERR::ResourceNotLocked;
      T *obj = nullptr;

      inline ScopedObjectLock(OBJECTID ObjectID, int Milliseconds = 3000) {
         error = AccessObject(ObjectID, Milliseconds, (OBJECTPTR *)&obj);
      }

      inline ScopedObjectLock(T *Object, int Milliseconds = 3000) {
         if (Object) {
            if (error = Object->lock(Milliseconds); error IS ERR::Okay) {
               obj = (T *)Object;
               quicklock = true;
            }
         }
      }

      inline ~ScopedObjectLock() {
         if (error IS ERR::Okay) {
            if (quicklock) obj->unlock();
            else ReleaseObject((OBJECTPTR)obj);
         }
      }

      inline void unlock() {
         if (error IS ERR::Okay) {
            if (quicklock) obj->unlock();
            else ReleaseObject((OBJECTPTR)obj);
            error = ERR::ResourceNotLocked;
         }
      }

      inline ScopedObjectLock() = default;

      // Copying or moving would result in a double-release of the lock.
      ScopedObjectLock(const ScopedObjectLock &) = delete;
      ScopedObjectLock & operator=(const ScopedObjectLock &) = delete;
      ScopedObjectLock(ScopedObjectLock &&) = delete;
      ScopedObjectLock & operator=(ScopedObjectLock &&) = delete;

      [[nodiscard]] inline bool granted() const { return error IS ERR::Okay; }

      inline T * operator->() { return obj; }; // Promotes underlying methods and fields
      inline T * & operator*() { return obj; }; // To allow object pointer referencing when calling functions
};

//********************************************************************************************************************
// Resource guard for any memory-based allocation that can be freed with FreeResource().  Retains the resource ID
// rather than the pointer to ensure that termination is safe, even if the original resource gets terminated
// elsewhere.
//
// For locally scoped allocations only; this class does not support reference counting.
//
// Usage: kt::LocalResource resource(thing)

template <class T>
class LocalResource {
   private:
      MEMORYID id;
   public:
      LocalResource(T Resource) {
         static_assert(std::is_pointer<T>::value, "The resource value must be a pointer");
         id = ((int *)Resource)[RESOURCE_ID_OFFSET];
      }
      ~LocalResource() { FreeResource(id); }

      // Copying or moving would result in a double-free of the resource.
      LocalResource(const LocalResource &) = delete;
      LocalResource & operator=(const LocalResource &) = delete;
      LocalResource(LocalResource &&) = delete;
      LocalResource & operator=(LocalResource &&) = delete;
};

//********************************************************************************************************************
// Enhanced version of LocalResource that features reference counting and is usable for object resources.  The use of
// GuardedObject is considered essential for interoperability with the C++ class destruction model.
// Uses concepts to ensure T derives from Object and C is a valid reference counter type.

template <class T = Object, RefCounter C = std::atomic_int>
   requires std::is_base_of_v<Object, T>
class GuardedObject {

   private:
      C * count;  // Count of GuardedObjects accessing the same resource.  Can be int (non-threaded) or std::atomic_int
      T * object; // Pointer to the Kotuku object being guarded.  Use '*' or '->' operators to access.

   public:
      OBJECTID id; // Object/Resource UID

      // Constructors

      GuardedObject() : count(new C(1)), object(nullptr), id(0) { }

      GuardedObject(T *pObject) : count(new C(1)), object(pObject) {
         if (pObject) id = ((OBJECTPTR)pObject)->UID;
         else id = 0;
      }

      GuardedObject(const GuardedObject &other) { // Copy constructor
         if (other.object) {
            object = other.object;
            count  = other.count;
            count[0]++;
            id     = other.id;
         }
         else { // If the other object is undefined then use a default state
            object = nullptr;
            id     = 0;
            count  = new C(1);
         }
      }

      GuardedObject(GuardedObject &&other) { // Move constructor
         id     = other.id;
         object = other.object;
         count  = other.count;
         other.count  = nullptr;
         other.object = nullptr;
         other.id     = 0;
      }

      // Destructor

      ~GuardedObject() {
         if (!count) return; // The count can be empty if this GuardedObject was moved

         if (!--count[0]) {
            if (id) FreeResource(id);
            delete count;
         }
      }

      GuardedObject & operator = (const GuardedObject &other) { // Copy assignment
         if (this == &other) return *this;
         if ((count) and (!--count[0])) {
            if (id) FreeResource(id);
            delete count;
         }
         if (other.object) {
            object = other.object;
            count  = other.count;
            count[0]++;
            id     = other.id;
         }
         else { // If the other object is undefined then we reset our state with no count inheritance.
            object = nullptr;
            id     = 0;
            count  = new C(1);
         }
         return *this;
      }

      GuardedObject & operator = (GuardedObject &&other) { // Move assignment
         if (this == &other) return *this;
         if ((count) and (!--count[0])) {
            if (id) FreeResource(id);
            delete count;
         }
         id     = other.id;
         object = other.object;
         count  = other.count;
         other.count  = nullptr;
         other.object = nullptr;
         other.id     = 0;
         return *this;
      }

      // Public methods

      inline void set(T *Object) { // set() requires caution as the object reference is modified without adjusting the counter
         if (!Object) return;
         else if (count[0] IS 1) {
            object = Object;
            id     = ((OBJECTPTR)Object)->UID;
         }
         else { kt::Log log(__FUNCTION__); log.warning(ERR::InUse); }
      }

      constexpr bool empty() const { return !object; } // Returns true if no object is being guarded.

      T * operator->() { return object; }; // Promotes underlying methods and fields
      T * & operator*() { return object; }; // To allow object pointer referencing when calling functions
};

//********************************************************************************************************************
// As for GuardedObject, but works with any resource type.

template <class T = void, class C = std::atomic_int>
class GuardedResource {
   private:
      C * count;  // Count of GuardedResources accessing the same resource.  Can be int (non-threaded) or std::atomic_int
      T * resource; // Pointer to the Kotuku resource being guarded.  Use '*' or '->' operators to access.

   public:
      MEMORYID id; // Resource UID

      // Constructors

      GuardedResource() : count(new C(1)), resource(nullptr), id(0) { }

      GuardedResource(T *Resource) : count(new C(1)), resource(Resource) {
         id = ((int *)Resource)[RESOURCE_ID_OFFSET];
      }

      GuardedResource(const GuardedResource &other) { // Copy constructor
         if (other.resource) {
            resource = other.resource;
            count    = other.count;
            count[0]++;
            id       = other.id;
         }
         else { // If the other resource is undefined then use a default state
            resource = nullptr;
            id       = 0;
            count    = new C(1);
         }
      }

      GuardedResource(GuardedResource &&other) { // Move constructor
         id       = other.id;
         resource = other.resource;
         count    = other.count;
         other.count    = nullptr;
         other.resource = nullptr;
         other.id       = 0;
      }

      // Destructor

      ~GuardedResource() {
         if (!count) return; // The count can be empty if this GuardedResource was moved

         if (!--count[0]) {
            if (id) FreeResource(id);
            delete count;
         }
      }

      GuardedResource & operator = (const GuardedResource &other) { // Copy assignment
         if (this == &other) return *this;
         if ((count) and (!--count[0])) {
            if (id) FreeResource(id);
            delete count;
         }
         if (other.resource) {
            resource = other.resource;
            count    = other.count;
            count[0]++;
            id       = other.id;
         }
         else { // If the other resource is undefined then we reset our state with no count inheritance.
            resource = nullptr;
            id       = 0;
            count    = new C(1);
         }
         return *this;
      }

      GuardedResource & operator = (GuardedResource &&other) { // Move assignment
         if (this == &other) return *this;
         if ((count) and (!--count[0])) {
            if (id) FreeResource(id);
            delete count;
         }
         id       = other.id;
         resource = other.resource;
         count    = other.count;
         other.count    = nullptr;
         other.resource = nullptr;
         other.id       = 0;
         return *this;
      }

      // Public methods

      inline void set(T *Resource) { // set() requires caution as the resource reference is modified without adjusting the counter
         if (!Resource) return;
         else if (count[0] IS 1) {
            resource = Resource;
            id       = ((int *)Resource)[RESOURCE_ID_OFFSET];
         }
         else { kt::Log log(__FUNCTION__); log.warning(ERR::InUse); }
      }

      constexpr bool empty() const { return !resource; } // Returns true if no resource is being guarded.

      T * operator->() { return resource; }; // Promotes underlying methods and fields
      T * & operator*() { return resource; }; // To allow resource pointer referencing when calling functions
};

//********************************************************************************************************************
// Resource guard for temporarily switching context and back when out of scope.  NOTE: It also acquires a lock on the
// target object, on the basis that we need to retain R/W access and prevent early termination while operating in the
// object's space.  In cases where this is undesirable, use direct calls to SetObjectContext().
//
// Usage: kt::SwitchContext context(YourObject)

template <class T>
class SwitchContext { // C++ wrapper for changing the current context with a resource guard in place
   private:
      T *object;
      bool restore;

   public:
      SwitchContext(T *NewContext) {
         if (NewContext) {
            object = NewContext;
            object->lock();
            SetObjectContext(NewContext, nullptr, AC::NIL);
            restore = true;
         }
         else { // A null object is legal - we just do nothing.
            object = nullptr;
            restore = false;
         }
      }
      ~SwitchContext() {
         if (object) ((OBJECTPTR)object)->unlock();
         if (restore) SetObjectContext(nullptr, nullptr, AC::NIL);
      }

      // Copying or moving would result in a double-unlock and unbalanced context restoration.
      SwitchContext(const SwitchContext &) = delete;
      SwitchContext & operator=(const SwitchContext &) = delete;
      SwitchContext(SwitchContext &&) = delete;
      SwitchContext & operator=(SwitchContext &&) = delete;
};

} // namespace

#include <kotuku/field_values.hpp>
