// Auto-generated by idl-c.tiri

static const struct FieldDef clTaskFlags[] = {
   { "Wait", 0x00000001 },
   { "ResetPath", 0x00000002 },
   { "Privileged", 0x00000004 },
   { "Shell", 0x00000008 },
   { "Verbose", 0x00000010 },
   { "Quiet", 0x00000020 },
   { "Detached", 0x00000040 },
   { "Attached", 0x00000080 },
   { "Pipe", 0x00000100 },
   { nullptr, 0 }
};

FDEF maAddArgument[] = { { "Argument", FDF_CPPSTRING }, { 0, 0 } };
FDEF maGetEnv[] = { { "Name", FDF_CPPSTRING }, { "Value", FD_RESULT|FD_MUTABLE|FDF_CPPSTRING }, { 0, 0 } };
FDEF maSetEnv[] = { { "Name", FDF_CPPSTRING }, { "Value", FDF_CPPSTRING }, { 0, 0 } };

static const struct MethodEntry clTaskMethods[] = {
   { AC(-1), (APTR)TASK_Expunge, "Expunge", 0, 0 },
   { AC(-2), (APTR)TASK_AddArgument, "AddArgument", maAddArgument, sizeof(struct task::AddArgument) },
   { AC(-3), (APTR)TASK_Quit, "Quit", 0, 0 },
   { AC(-4), (APTR)TASK_GetEnv, "GetEnv", maGetEnv, sizeof(struct task::GetEnv) },
   { AC(-5), (APTR)TASK_SetEnv, "SetEnv", maSetEnv, sizeof(struct task::SetEnv) },
   { AC::NIL, 0, 0, 0, 0 }
};

static ERR TASK_NewPlacement(extTask *Self) {
   new (Self) extTask;
   return ERR::Okay;
}

static ERR TASK_FreePlacement(extTask *Self) {
   Self->~extTask();
   return ERR::Okay;
}

static const struct ActionArray clTaskActions[] = {
   { AC::Activate, TASK_Activate },
   { AC::Free, TASK_Free },
   { AC::FreePlacement, TASK_FreePlacement },
   { AC::GetKey, TASK_GetKey },
   { AC::Init, TASK_Init },
   { AC::NewPlacement, TASK_NewPlacement },
   { AC::Query, TASK_Query },
   { AC::SetKey, TASK_SetKey },
   { AC::Write, TASK_Write },
   { AC::NIL, nullptr }
};

