// Auto-generated by idl-c.tiri

static const struct FieldDef clFileFlags[] = {
   { "Write", 0x00000001 },
   { "New", 0x00000002 },
   { "Read", 0x00000004 },
   { "Directory", 0x00000008 },
   { "Folder", 0x00000008 },
   { "Approximate", 0x00000010 },
   { "Link", 0x00000020 },
   { "Buffer", 0x00000040 },
   { "Loop", 0x00000080 },
   { "File", 0x00000100 },
   { "ResetDate", 0x00000200 },
   { "Device", 0x00000400 },
   { "Stream", 0x00000800 },
   { "ExcludeFiles", 0x00001000 },
   { "ExcludeFolders", 0x00002000 },
   { "Virtual", 0x00004000 },
   { nullptr, 0 }
};

static const struct FieldDef clFilePermissions[] = {
   { "Read", 0x00000001 },
   { "UserRead", 0x00000001 },
   { "UserWrite", 0x00000002 },
   { "Write", 0x00000002 },
   { "Exec", 0x00000004 },
   { "UserExec", 0x00000004 },
   { "Delete", 0x00000008 },
   { "User", 0x0000000f },
   { "GroupRead", 0x00000010 },
   { "GroupWrite", 0x00000020 },
   { "GroupExec", 0x00000040 },
   { "GroupDelete", 0x00000080 },
   { "Group", 0x000000f0 },
   { "OthersRead", 0x00000100 },
   { "AllRead", 0x00000111 },
   { "EveryoneRead", 0x00000111 },
   { "OthersWrite", 0x00000200 },
   { "AllWrite", 0x00000222 },
   { "EveryoneWrite", 0x00000222 },
   { "EveryoneReadwrite", 0x00000333 },
   { "OthersExec", 0x00000400 },
   { "AllExec", 0x00000444 },
   { "EveryoneExec", 0x00000444 },
   { "OthersDelete", 0x00000800 },
   { "AllDelete", 0x00000888 },
   { "EveryoneDelete", 0x00000888 },
   { "Others", 0x00000f00 },
   { "EveryoneAccess", 0x00000fff },
   { "Hidden", 0x00001000 },
   { "Archive", 0x00002000 },
   { "Password", 0x00004000 },
   { "Userid", 0x00008000 },
   { "Groupid", 0x00010000 },
   { "Inherit", 0x00020000 },
   { "Offline", 0x00040000 },
   { "Network", 0x00080000 },
   { "Meta", 0x000c5000 },
   { nullptr, 0 }
};

static const struct FieldDef clFilePERMIT[] = {
   { "Read", 0x00000001 },
   { "UserRead", 0x00000001 },
   { "UserWrite", 0x00000002 },
   { "Write", 0x00000002 },
   { "Exec", 0x00000004 },
   { "UserExec", 0x00000004 },
   { "Delete", 0x00000008 },
   { "User", 0x0000000f },
   { "GroupRead", 0x00000010 },
   { "GroupWrite", 0x00000020 },
   { "GroupExec", 0x00000040 },
   { "GroupDelete", 0x00000080 },
   { "Group", 0x000000f0 },
   { "OthersRead", 0x00000100 },
   { "AllRead", 0x00000111 },
   { "EveryoneRead", 0x00000111 },
   { "OthersWrite", 0x00000200 },
   { "AllWrite", 0x00000222 },
   { "EveryoneWrite", 0x00000222 },
   { "EveryoneReadwrite", 0x00000333 },
   { "OthersExec", 0x00000400 },
   { "AllExec", 0x00000444 },
   { "EveryoneExec", 0x00000444 },
   { "OthersDelete", 0x00000800 },
   { "AllDelete", 0x00000888 },
   { "EveryoneDelete", 0x00000888 },
   { "Others", 0x00000f00 },
   { "EveryoneAccess", 0x00000fff },
   { "Hidden", 0x00001000 },
   { "Archive", 0x00002000 },
   { "Password", 0x00004000 },
   { "Userid", 0x00008000 },
   { "Groupid", 0x00010000 },
   { "Inherit", 0x00020000 },
   { "Offline", 0x00040000 },
   { "Network", 0x00080000 },
   { "Meta", 0x000c5000 },
   { nullptr, 0 }
};

FDEF maStartStream[] = { { "Subscriber", FD_OBJECTID }, { "Flags", FD_INT }, { "Length", FD_INT }, { 0, 0 } };
FDEF maDelete[] = { { "Callback", FD_FUNCTIONPTR }, { 0, 0 } };
FDEF maMove[] = { { "Dest", FDF_CPPSTRING }, { "Callback", FD_FUNCTIONPTR }, { 0, 0 } };
FDEF maCopy[] = { { "Dest", FDF_CPPSTRING }, { "Callback", FD_FUNCTIONPTR }, { 0, 0 } };
FDEF maSetDate[] = { { "Year", FD_INT }, { "Month", FD_INT }, { "Day", FD_INT }, { "Hour", FD_INT }, { "Minute", FD_INT }, { "Second", FD_INT }, { "Type", FD_INT }, { 0, 0 } };
FDEF maReadLine[] = { { "Result", FD_RESULT|FD_MUTABLE|FDF_CPPSTRING }, { 0, 0 } };
FDEF maNext[] = { { "File", FD_RESULT|FD_OBJECTPTR|FD_ALLOC }, { 0, 0 } };
FDEF maWatch[] = { { "Callback", FD_FUNCTIONPTR }, { "Flags", FD_INT }, { 0, 0 } };

static const struct MethodEntry clFileMethods[] = {
   { AC(-1), (APTR)FILE_StartStream, "StartStream", maStartStream, sizeof(struct fl::StartStream) },
   { AC(-2), (APTR)FILE_StopStream, "StopStream", 0, 0 },
   { AC(-3), (APTR)FILE_Delete, "Delete", maDelete, sizeof(struct fl::Delete) },
   { AC(-4), (APTR)FILE_MoveFile, "Move", maMove, sizeof(struct fl::Move) },
   { AC(-5), (APTR)FILE_Copy, "Copy", maCopy, sizeof(struct fl::Copy) },
   { AC(-6), (APTR)FILE_SetDate, "SetDate", maSetDate, sizeof(struct fl::SetDate) },
   { AC(-7), (APTR)FILE_ReadLine, "ReadLine", maReadLine, sizeof(struct fl::ReadLine) },
   { AC(-8), (APTR)FILE_BufferContent, "BufferContent", 0, 0 },
   { AC(-9), (APTR)FILE_NextFile, "Next", maNext, sizeof(struct fl::Next) },
   { AC(-10), (APTR)FILE_Watch, "Watch", maWatch, sizeof(struct fl::Watch) },
   { AC::NIL, 0, 0, 0, 0 }
};

static ERR FILE_NewPlacement(extFile *Self) {
   new (Self) extFile(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR FILE_FreePlacement(extFile *Self) {
   Self->~extFile();
   return ERR::Okay;
}

static const struct ActionArray clFileActions[] = {
   { AC::Activate, FILE_Activate },
   { AC::DataFeed, FILE_DataFeed },
   { AC::Flush, FILE_Flush },
   { AC::FreePlacement, FILE_FreePlacement },
   { AC::Init, FILE_Init },
   { AC::NewPlacement, FILE_NewPlacement },
   { AC::Query, FILE_Query },
   { AC::Read, FILE_Read },
   { AC::Rename, FILE_Rename },
   { AC::Reset, FILE_Reset },
   { AC::Seek, FILE_Seek },
   { AC::Write, FILE_Write },
   { AC::NIL, nullptr }
};

