// Auto-generated by idl-c.tiri

static const struct FieldDef clThreadFlags[] = {
   { "AutoFree", 0x00000001 },
   { nullptr, 0 }
};

FDEF maSetData[] = { { "Data", FD_BUFFER|FD_PTR }, { "Size", FD_INT|FD_BUFSIZE }, { 0, 0 } };

static const struct MethodEntry clThreadMethods[] = {
   { AC(-1), (APTR)THREAD_SetData, "SetData", maSetData, sizeof(struct th::SetData) },
   { AC::NIL, 0, 0, 0, 0 }
};

static ERR THREAD_NewPlacement(extThread *Self) {
   new (Self) extThread;
   return ERR::Okay;
}

static ERR THREAD_FreePlacement(extThread *Self) {
   Self->~extThread();
   return ERR::Okay;
}

static const struct ActionArray clThreadActions[] = {
   { AC::Activate, THREAD_Activate },
   { AC::Deactivate, THREAD_Deactivate },
   { AC::FreePlacement, THREAD_FreePlacement },
   { AC::FreeWarning, THREAD_FreeWarning },
   { AC::NewPlacement, THREAD_NewPlacement },
   { AC::NIL, nullptr }
};

