// Auto-generated by idl-c.tiri

static const struct FieldDef clStorageDeviceDeviceFlags[] = {
   { "CompactDisc", 0x00000001 },
   { "HardDisk", 0x00000002 },
   { "FloppyDisk", 0x00000004 },
   { "Read", 0x00000008 },
   { "Write", 0x00000010 },
   { "Removable", 0x00000020 },
   { "Removeable", 0x00000020 },
   { "Software", 0x00000040 },
   { "Network", 0x00000080 },
   { "Tape", 0x00000100 },
   { "Printer", 0x00000200 },
   { "Scanner", 0x00000400 },
   { "Temporary", 0x00000800 },
   { "Memory", 0x00001000 },
   { "Modem", 0x00002000 },
   { "Usb", 0x00004000 },
   { "Fixed", 0x00008000 },
   { "Printer3D", 0x00010000 },
   { "Scanner3D", 0x00020000 },
   { "Bookmark", 0x00040000 },
   { nullptr, 0 }
};

static ERR STORAGEDEVICE_NewPlacement(objStorageDevice *Self) {
   new (Self) objStorageDevice;
   return ERR::Okay;
}

static ERR STORAGEDEVICE_FreePlacement(objStorageDevice *Self) {
   Self->~objStorageDevice();
   return ERR::Okay;
}

static const struct ActionArray clStorageDeviceActions[] = {
   { AC::FreePlacement, STORAGEDEVICE_FreePlacement },
   { AC::Init, STORAGEDEVICE_Init },
   { AC::NewPlacement, STORAGEDEVICE_NewPlacement },
   { AC::NIL, nullptr }
};

