// Auto-generated by idl-c.tiri

static const struct FieldDef clThreadFlags[] = {
   { "AutoFree", 0x00000001 },
   { nullptr, 0 }
};

static ERR THREAD_New(extThread *Self) {
   new (Self) extThread(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR THREAD_Free(extThread *Self) {
   Self->~extThread();
   return ERR::Okay;
}

static const struct ActionArray clThreadActions[] = {
   { AC::Activate, THREAD_Activate },
   { AC::Deactivate, THREAD_Deactivate },
   { AC::Free, THREAD_Free },
   { AC::FreeWarning, THREAD_FreeWarning },
   { AC::New, THREAD_New },
   { AC::NIL, nullptr }
};

