// Auto-generated by idl-c.tiri

FDEF maGetTimeZoneInfo[] = { { "ZoneID", FDF_CPPSTRING }, { "StartYear", FD_INT }, { "EndYear", FD_INT }, { "TimeZoneInfo:Info", FD_RESULT|FD_PTR|FD_STRUCT|FD_ALLOC }, { 0, 0 } };

static const struct MethodEntry clTimeMethods[] = {
   { AC(-1), (APTR)TIME_SetTime, "SetTime", 0, 0 },
   { AC(-2), (APTR)TIME_GetTimeZoneInfo, "GetTimeZoneInfo", maGetTimeZoneInfo, sizeof(struct pt::GetTimeZoneInfo) },
   { AC::NIL, 0, 0, 0, 0 }
};

static ERR TIME_NewPlacement(objTime *Self) {
   new (Self) objTime(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR TIME_FreePlacement(objTime *Self) {
   Self->~objTime();
   return ERR::Okay;
}

static const struct ActionArray clTimeActions[] = {
   { AC::FreePlacement, TIME_FreePlacement },
   { AC::NewPlacement, TIME_NewPlacement },
   { AC::Query, TIME_Query },
   { AC::Refresh, TIME_Refresh },
   { AC::NIL, nullptr }
};

