// Auto-generated by idl-c.tiri

static ERR AUDIOLIMITER_New(extAudioLimiter *Self) {
   new (Self) extAudioLimiter(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR AUDIOLIMITER_Free(extAudioLimiter *Self) {
   Self->~extAudioLimiter();
   return ERR::Okay;
}

static const struct ActionArray clAudioLimiterActions[] = {
   { AC::Free, AUDIOLIMITER_Free },
   { AC::Init, AUDIOLIMITER_Init },
   { AC::New, AUDIOLIMITER_New },
   { AC::NIL, nullptr }
};

