// Auto-generated by idl-c.tiri

static ERR AUDIOCHORUS_New(extAudioChorus *Self) {
   new (Self) extAudioChorus(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR AUDIOCHORUS_Free(extAudioChorus *Self) {
   Self->~extAudioChorus();
   return ERR::Okay;
}

static const struct ActionArray clAudioChorusActions[] = {
   { AC::Free, AUDIOCHORUS_Free },
   { AC::Init, AUDIOCHORUS_Init },
   { AC::New, AUDIOCHORUS_New },
   { AC::NIL, nullptr }
};

