// Auto-generated by idl-c.tiri

static ERR AUDIOEQUALISER_New(extAudioEqualiser *Self) {
   new (Self) extAudioEqualiser(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR AUDIOEQUALISER_Free(extAudioEqualiser *Self) {
   Self->~extAudioEqualiser();
   return ERR::Okay;
}

static const struct ActionArray clAudioEqualiserActions[] = {
   { AC::Free, AUDIOEQUALISER_Free },
   { AC::Init, AUDIOEQUALISER_Init },
   { AC::New, AUDIOEQUALISER_New },
   { AC::NIL, nullptr }
};

