// Auto-generated by idl-c.tiri

static ERR AUDIOPITCHSHIFT_New(extAudioPitchShift *Self) {
   new (Self) extAudioPitchShift(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR AUDIOPITCHSHIFT_Free(extAudioPitchShift *Self) {
   Self->~extAudioPitchShift();
   return ERR::Okay;
}

static const struct ActionArray clAudioPitchShiftActions[] = {
   { AC::Free, AUDIOPITCHSHIFT_Free },
   { AC::Init, AUDIOPITCHSHIFT_Init },
   { AC::New, AUDIOPITCHSHIFT_New },
   { AC::NIL, nullptr }
};

