// Auto-generated by idl-c.tiri

static ERR AUDIOCOMPRESSOR_New(extAudioCompressor *Self) {
   new (Self) extAudioCompressor(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR AUDIOCOMPRESSOR_Free(extAudioCompressor *Self) {
   Self->~extAudioCompressor();
   return ERR::Okay;
}

static const struct ActionArray clAudioCompressorActions[] = {
   { AC::Free, AUDIOCOMPRESSOR_Free },
   { AC::Init, AUDIOCOMPRESSOR_Init },
   { AC::New, AUDIOCOMPRESSOR_New },
   { AC::NIL, nullptr }
};

