// Auto-generated by idl-c.tiri

static ERR AUDIOGATE_New(extAudioGate *Self) {
   new (Self) extAudioGate(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR AUDIOGATE_Free(extAudioGate *Self) {
   Self->~extAudioGate();
   return ERR::Okay;
}

static const struct ActionArray clAudioGateActions[] = {
   { AC::Free, AUDIOGATE_Free },
   { AC::Init, AUDIOGATE_Init },
   { AC::New, AUDIOGATE_New },
   { AC::NIL, nullptr }
};

