// Auto-generated by idl-c.tiri

static ERR AUDIOREVERB_New(extAudioReverb *Self) {
   new (Self) extAudioReverb(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR AUDIOREVERB_Free(extAudioReverb *Self) {
   Self->~extAudioReverb();
   return ERR::Okay;
}

static const struct ActionArray clAudioReverbActions[] = {
   { AC::Free, AUDIOREVERB_Free },
   { AC::Init, AUDIOREVERB_Init },
   { AC::New, AUDIOREVERB_New },
   { AC::NIL, nullptr }
};

