// Auto-generated by idl-c.tiri

static ERR AUDIOSTEREO_New(extAudioStereo *Self) {
   new (Self) extAudioStereo(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR AUDIOSTEREO_Free(extAudioStereo *Self) {
   Self->~extAudioStereo();
   return ERR::Okay;
}

static const struct ActionArray clAudioStereoActions[] = {
   { AC::Free, AUDIOSTEREO_Free },
   { AC::Init, AUDIOSTEREO_Init },
   { AC::New, AUDIOSTEREO_New },
   { AC::NIL, nullptr }
};

