// Auto-generated by idl-c.tiri

static ERR AUDIOSPLITTER_New(extAudioSplitter *Self) {
   new (Self) extAudioSplitter(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR AUDIOSPLITTER_Free(extAudioSplitter *Self) {
   Self->~extAudioSplitter();
   return ERR::Okay;
}

static const struct ActionArray clAudioSplitterActions[] = {
   { AC::Free, AUDIOSPLITTER_Free },
   { AC::Init, AUDIOSPLITTER_Init },
   { AC::New, AUDIOSPLITTER_New },
   { AC::NIL, nullptr }
};

