// Auto-generated by idl-c.tiri

static ERR AUDIOCROSSFEED_New(extAudioCrossfeed *Self) {
   new (Self) extAudioCrossfeed(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR AUDIOCROSSFEED_Free(extAudioCrossfeed *Self) {
   Self->~extAudioCrossfeed();
   return ERR::Okay;
}

static const struct ActionArray clAudioCrossfeedActions[] = {
   { AC::Free, AUDIOCROSSFEED_Free },
   { AC::Init, AUDIOCROSSFEED_Init },
   { AC::New, AUDIOCROSSFEED_New },
   { AC::NIL, nullptr }
};

