// Auto-generated by idl-c.tiri

static ERR AUDIODELAY_New(extAudioDelay *Self) {
   new (Self) extAudioDelay(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR AUDIODELAY_Free(extAudioDelay *Self) {
   Self->~extAudioDelay();
   return ERR::Okay;
}

static const struct ActionArray clAudioDelayActions[] = {
   { AC::Free, AUDIODELAY_Free },
   { AC::Init, AUDIODELAY_Init },
   { AC::New, AUDIODELAY_New },
   { AC::NIL, nullptr }
};

