// Auto-generated by idl-c.tiri

static const struct FieldDef clSoundFlags[] = {
   { "Loop", 0x00000001 },
   { "New", 0x00000002 },
   { "Stereo", 0x00000004 },
   { "RestrictPlay", 0x00000008 },
   { "Stream", 0x40000000 },
   { "Note", (int)0x80000000 },
   { nullptr, 0 }
};

static const struct FieldDef clSoundStream[] = {
   { "Never", 0x00000001 },
   { "Smart", 0x00000002 },
   { "Always", 0x00000003 },
   { nullptr, 0 }
};

static const struct ActionArray clSoundActions[] = {
   { AC::Activate, SOUND_Activate },
   { AC::Deactivate, SOUND_Deactivate },
   { AC::Disable, SOUND_Disable },
   { AC::Enable, SOUND_Enable },
   { AC::Free, SOUND_Free },
   { AC::GetKey, SOUND_GetKey },
   { AC::Init, SOUND_Init },
   { AC::NewPlacement, SOUND_NewPlacement },
   { AC::Read, SOUND_Read },
   { AC::SaveToObject, SOUND_SaveToObject },
   { AC::Seek, SOUND_Seek },
   { AC::SetKey, SOUND_SetKey },
   { AC::NIL, nullptr }
};

