// Auto-generated by idl-c.tiri

static ERR AUDIOFLANGER_New(extAudioFlanger *Self) {
   new (Self) extAudioFlanger(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR AUDIOFLANGER_Free(extAudioFlanger *Self) {
   Self->~extAudioFlanger();
   return ERR::Okay;
}

static const struct ActionArray clAudioFlangerActions[] = {
   { AC::Free, AUDIOFLANGER_Free },
   { AC::Init, AUDIOFLANGER_Init },
   { AC::New, AUDIOFLANGER_New },
   { AC::NIL, nullptr }
};

