// Auto-generated by idl-c.tiri

static ERR AUDIOLOUDNESS_New(extAudioLoudness *Self) {
   new (Self) extAudioLoudness(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR AUDIOLOUDNESS_Free(extAudioLoudness *Self) {
   Self->~extAudioLoudness();
   return ERR::Okay;
}

static const struct ActionArray clAudioLoudnessActions[] = {
   { AC::Free, AUDIOLOUDNESS_Free },
   { AC::Init, AUDIOLOUDNESS_Init },
   { AC::New, AUDIOLOUDNESS_New },
   { AC::NIL, nullptr }
};

