// Auto-generated by idl-c.tiri

static ERR AUDIOSATURATOR_New(extAudioSaturator *Self) {
   new (Self) extAudioSaturator(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR AUDIOSATURATOR_Free(extAudioSaturator *Self) {
   Self->~extAudioSaturator();
   return ERR::Okay;
}

static const struct ActionArray clAudioSaturatorActions[] = {
   { AC::Free, AUDIOSATURATOR_Free },
   { AC::Init, AUDIOSATURATOR_Init },
   { AC::New, AUDIOSATURATOR_New },
   { AC::NIL, nullptr }
};

