// Auto-generated by idl-c.tiri

static ERR AUDIOPHASER_New(extAudioPhaser *Self) {
   new (Self) extAudioPhaser(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR AUDIOPHASER_Free(extAudioPhaser *Self) {
   Self->~extAudioPhaser();
   return ERR::Okay;
}

static const struct ActionArray clAudioPhaserActions[] = {
   { AC::Free, AUDIOPHASER_Free },
   { AC::Init, AUDIOPHASER_Init },
   { AC::New, AUDIOPHASER_New },
   { AC::NIL, nullptr }
};

