// Auto-generated by idl-c.tiri

FDEF maGetSpectrum[] = { { "Frequencies", FDF_SPAN|FD_DOUBLE }, { "Levels", FDF_SPAN|FD_MUTABLE|FD_DOUBLE }, { 0, 0 } };
FDEF maGetWaveform[] = { { "Samples", FDF_SPAN|FD_MUTABLE|FD_FLOAT }, { 0, 0 } };

static const struct MethodEntry clAudioAnalyserMethods[] = {
   { AC(-30), (APTR)AUDIOANALYSER_GetSpectrum, "GetSpectrum", maGetSpectrum, sizeof(struct ana::GetSpectrum) },
   { AC(-31), (APTR)AUDIOANALYSER_GetWaveform, "GetWaveform", maGetWaveform, sizeof(struct ana::GetWaveform) },
   { AC::NIL, 0, 0, 0, 0 }
};

static ERR AUDIOANALYSER_New(extAudioAnalyser *Self) {
   new (Self) extAudioAnalyser(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR AUDIOANALYSER_Free(extAudioAnalyser *Self) {
   Self->~extAudioAnalyser();
   return ERR::Okay;
}

static const struct ActionArray clAudioAnalyserActions[] = {
   { AC::Free, AUDIOANALYSER_Free },
   { AC::Init, AUDIOANALYSER_Init },
   { AC::New, AUDIOANALYSER_New },
   { AC::NIL, nullptr }
};

