// Auto-generated by idl-c.tiri

static const struct FieldDef clHashAlgorithm[] = {
   { "Md5", 0x00000001 },
   { "Sha1", 0x00000002 },
   { "Sha256", 0x00000003 },
   { "Sha512", 0x00000004 },
   { nullptr, 0 }
};

FDEF maUpdate[] = { { "Data", FDF_SPAN|FD_BYTE }, { 0, 0 } };
FDEF maDigest[] = { { "Output", FDF_SPAN|FD_MUTABLE|FD_BYTE }, { 0, 0 } };

static const struct MethodEntry clHashMethods[] = {
   { AC(-1), (APTR)HASH_Update, "Update", maUpdate, sizeof(struct hsh::Update) },
   { AC(-2), (APTR)HASH_Digest, "Digest", maDigest, sizeof(struct hsh::Digest) },
   { AC::NIL, 0, 0, 0, 0 }
};

static ERR HASH_New(extHash *Self) {
   new (Self) extHash(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR HASH_Free(extHash *Self) {
   Self->~extHash();
   return ERR::Okay;
}

static const struct ActionArray clHashActions[] = {
   { AC::Free, HASH_Free },
   { AC::Init, HASH_Init },
   { AC::New, HASH_New },
   { AC::Reset, HASH_Reset },
   { AC::NIL, nullptr }
};

