// Auto-generated by idl-c.tiri

static const struct FieldDef clVectorSceneFlags[] = {
   { "BitmapSized", 0x00000001 },
   { "RenderTime", 0x00000002 },
   { "Resize", 0x00000004 },
   { "OutlineViewports", 0x00000008 },
   { "StableRender", 0x00000010 },
   { nullptr, 0 }
};

static const struct FieldDef clVectorSceneSampleMethod[] = {
   { "Auto", 0x00000000 },
   { "Neighbour", 0x00000001 },
   { "Bilinear", 0x00000002 },
   { "Bicubic", 0x00000003 },
   { "Spline16", 0x00000004 },
   { "Kaiser", 0x00000005 },
   { "Quadric", 0x00000006 },
   { "Gaussian", 0x00000007 },
   { "Bessel", 0x00000008 },
   { "Mitchell", 0x00000009 },
   { "Sinc", 0x0000000a },
   { "Lanczos", 0x0000000b },
   { "Blackman", 0x0000000c },
   { nullptr, 0 }
};

FDEF maAddDef[] = { { "Name", FDF_CPPSTRING }, { "Def", FD_OBJECTPTR }, { 0, 0 } };
FDEF maSearchByID[] = { { "ID", FD_INT }, { "Result", FD_RESULT|FD_OBJECTPTR }, { 0, 0 } };
FDEF maFindDef[] = { { "Name", FDF_CPPSTRING }, { "Def", FD_RESULT|FD_OBJECTPTR }, { 0, 0 } };

static const struct MethodEntry clVectorSceneMethods[] = {
   { AC(-1), (APTR)VECTORSCENE_AddDef, "AddDef", maAddDef, sizeof(struct sc::AddDef) },
   { AC(-2), (APTR)VECTORSCENE_SearchByID, "SearchByID", maSearchByID, sizeof(struct sc::SearchByID) },
   { AC(-3), (APTR)VECTORSCENE_FindDef, "FindDef", maFindDef, sizeof(struct sc::FindDef) },
   { AC(-4), (APTR)VECTORSCENE_Debug, "Debug", 0, 0 },
   { AC::NIL, 0, 0, 0, 0 }
};

static ERR VECTORSCENE_NewPlacement(extVectorScene *Self) {
   new (Self) extVectorScene;
   return ERR::Okay;
}

static ERR VECTORSCENE_FreePlacement(extVectorScene *Self) {
   Self->~extVectorScene();
   return ERR::Okay;
}

static const struct ActionArray clVectorSceneActions[] = {
   { AC::Draw, VECTORSCENE_Draw },
   { AC::Flush, VECTORSCENE_Flush },
   { AC::Free, VECTORSCENE_Free },
   { AC::FreePlacement, VECTORSCENE_FreePlacement },
   { AC::Init, VECTORSCENE_Init },
   { AC::NewPlacement, VECTORSCENE_NewPlacement },
   { AC::Redimension, VECTORSCENE_Redimension },
   { AC::Reset, VECTORSCENE_Reset },
   { AC::Resize, VECTORSCENE_Resize },
   { AC::NIL, nullptr }
};

