// Auto-generated by idl-c.tiri

static const struct FieldDef clClientSocketState[] = {
   { "Disconnected", 0x00000000 },
   { "Resolving", 0x00000001 },
   { "Connecting", 0x00000002 },
   { "Handshaking", 0x00000003 },
   { "Connected", 0x00000004 },
   { "Multistate", 0x00000005 },
   { nullptr, 0 }
};

static ERR CLIENTSOCKET_NewPlacement(extClientSocket *Self) {
   new (Self) extClientSocket(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR CLIENTSOCKET_FreePlacement(extClientSocket *Self) {
   Self->~extClientSocket();
   return ERR::Okay;
}

static const struct ActionArray clClientSocketActions[] = {
   { AC::Deactivate, CLIENTSOCKET_Deactivate },
   { AC::FreePlacement, CLIENTSOCKET_FreePlacement },
   { AC::Init, CLIENTSOCKET_Init },
   { AC::NewPlacement, CLIENTSOCKET_NewPlacement },
   { AC::Read, CLIENTSOCKET_Read },
   { AC::Write, CLIENTSOCKET_Write },
   { AC::NIL, nullptr }
};

