const CSTRING glMessages[int(ERR::END)+1] = {
 "Operation successful",
 "The result is false",
 "Limited success",
 "Operation cancelled",
 "Nothing to do for the requested operation",
 "Please continue processing",
 "Skip this operation",
 "Retry the operation (could not succeed at this time)",
 "The end of the sequence has been reached",
 "Termination requested",
 "Not enough memory available",
 "One or more unit tests reported a failure",
 "Resource is in use",
 "General failure",
 "File error, e.g. file not found",
 "There is an error in the provided data",
 "A search routine in this function failed",
 "Trouble initialising/using a module",
 "File not found",
 "Wrong version, or version not supported",
 "Invalid arguments passed to function",
 "No data is available for use",
 "Error reading data",
 "Error writing data",
 "Failed to lock a required resource",
 "The server returned an HTTP status code outside the 2xx range",
 "The object has lost its class reference",
 "The object does not support this operation",
 "Operation not supported",
 "General memory error",
 "Function timed-out before successful completion",
 "Unspecified failure during decryption of a data stream",
 "Array is at low capacity",
 "Error in Init()ialising an object",
 "General security violation",
 "System corruption detected",
 "Unspecified failure during encryption of a data stream",
 "A secure connection handshake failed",
 "A compatible version of the Core is required",
 "A TLS certificate, private key or trust store could not be loaded",
 "Module validation has failed",
 "Process creation has failed",
 "Class name not provided",
 "A value is outside of the valid range",
 "Failed to register a resource with the system",
 "Array has reached capacity and cannot be expanded",
 "Attempt to Query() failed",
 "Deprecated error code",
 "Do not expunge yet",
 "Deprecated error code",
 "Requested field not found",
 "Invalid file or folder path detected",
 "An unspecific error occurred during a SetField() operation",
 "A resource cannot be accessed as it is marked for deletion",
 "Deprecated error code",
 "Deprecated error code",
 "Module failed in its Open routine",
 "Duplicate value not permitted",
 "Deprecated error code",
 "Module has not defined support for Init()",
 "Deprecated error code",
 "Audio mixing failed",
 "Dead-lock detected - procedure aborted",
 "Part of the system is unreachable due to a persistent lock",
 "Module has not declared an official name",
 "An error occurred while creating a new class",
 "Error while Activate()ing an object",
 "Warning - Attempt to initialise a resource twice",
 "A required field value is undefined",
 "The class could not be found in the system",
 "The File flag FL::READ was not set on initialisation",
 "The File flag FL::WRITE was not set on initialisation",
 "Deprecated error code",
 "The class does not export any methods",
 "No matching object was found for the given object ID",
 "Cannot modify an immutable field value",
 "The object is missing a path reference",
 "A lock was expected but not found",
 "The search yielded no results",
 "Deprecated error code",
 "The object structure is corrupt or has not been initialised",
 "Container pass through notification",
 "The owner is not supported by this object",
 "Attempting to lock an object failed",
 "Failed to create a new memory block",
 "NewObject() failed to produce a new object",
 "GetField() failed to retrieve a field value",
 "Access to a field was denied",
 "ResolvePath() failed to resolve the path because it is a virtual reference",
 "A dimension specification is invalid",
 "Field type mismatch while getting or setting a field",
 "A field type ID (e.g. INT, FLOAT) is not recognised",
 "A buffer overflow has occurred",
 "The specified field is not supported by the object's class",
 "A mis-match has been detected that prevents further processing",
 "Out-of-bounds access denied",
 "An error occurred during a seek operation",
 "Deprecated error code",
 "An infinite loop was detected",
 "The destination file or folder already exists",
 "A call to ResolvePath() failed",
 "A call to CreateObject() failed",
 "Deprecated error code",
 "The resource has not been initialised",
 "A new resource could not be created because a matching resource exists",
 "Deprecated error code",
 "Deprecated error code",
 "A call to the host system has failed",
 "Deprecated error code",
 "A required string value contains no characters",
 "Object exists",
 "The operation expected a path to a file",
 "Failure during the resize of an object",
 "Failure during the redimensioning of an object",
 "A semaphore operation failed",
 "Field validation failed",
 "A new file could not be created",
 "Deletion of a folder or file failed (e.g. permissions, read-only media)",
 "The file could not be opened",
 "A delete or write operation failed due to read-only status",
 "Resource does not exist",
 "The destination path is the same as the source path",
 "Resource exists",
 "Deprecated error code",
 "Out of space.  There is no available room to complete the request",
 "GetSurfaceInfo() failed",
 "Operation finished",
 "Invalid syntax detected",
 "Object was in an incorrect state for the operation",
 "The Internet host name could not be resolved",
 "Invalid Uniform Resource Identifier",
 "The remote host refused the connection",
 "The network was unreachable",
 "No route to host",
 "Device or end-point disconnected",
 "Task/Process still exists and is running",
 "Referential integrity / constraint violation",
 "Record changes would violate the DB schema",
 "The size of a data chunk or buffer is incorrect",
 "Operation cannot complete because system is busy with an earlier operation",
 "Attempt to connect to server aborted",
 "Function call missing argument value(s)",
 "An object is not of the required class type",
 "Execution violation - function must be called from the task that owns the object",
 "Detected an illegal attempt at recursion",
 "Address pointer is outside of the task's memory map",
 "The XML tags do not balance",
 "Requested operation would block if performed at this time",
 "Unspecified I/O error",
 "Failed to load a module binary",
 "A required handle is invalid",
 "Unspecified security violation",
 "A value has not passed validation",
 "Deprecated error code",
 "Deprecated error code",
 "Deprecated error code",
 "Object or resource has already been locked",
 "Deprecated error code",
 "Deprecated error code",
 "Failed to establish an SSL connection with the proxy server",
 "A valid HTTP response was not received from the server",
 "Deprecated error code",
 "An exception was caught",
 "Cannot execute a thread that is already running",
 "Failure reported from OpenGL",
 "Operation permitted from the main thread only",
 "Requested to use a registered derived class (not an error)",
 "The provided value does not match the expected type",
 "Thread objects must be locked prior to activation",
 "A message queue operation has failed",
 "A call to SetVolume() failed",
 "Unspecified failure during decompression of a data stream",
 "Unspecified failure during compression of a data stream",
 "The operation expected a folder path",
 "This operation would violate the object's immutable status",
 "A call to ReadFileToBuffer() failed",
 "This feature is no longer available (obsolete)",
 "Failed to create a new resource",
 "It is not possible to perform the requested operation",
 "Failed to resolve a linked library symbol",
 "A function call failed",
 "Attempted to change a value that cannot be redefined",
 "Attempted to set a numeric field with an incompatible value",
 "Deprecated error code",
 "Attempted to set an object field with an incompatible value",
 "Attempted to set a function field with an incompatible value",
 "Attempted to set a pointer field with an incompatible value",
 "Attempted to set an array field with an incompatible value",
 "Attempted to set a lookup field with an incompatible value",
 "The type of a value is invalid",
 "A compression stream operation has failed",
 "Task or process execution has failed",
 "The compression data is invalid or corrupted",
 "A sanity check has failed",
 "Client is not authorised to perform this operation",
 "The specified property is not recognised",
 "A secure sockets layer is not available in this environment",
 "Missing required parameter",
 "Unknown parameter name",
 "Attempted to set a struct field with an incompatible value",
 nullptr // Needs to be null-terminated for Tiri support
};

const int glTotalMessages = std::ssize(glMessages);
