// Auto-generated by idl-c.tiri

static const struct FieldDef clTiriJOF[] = {
   { "Diagnose", 0x00000001 },
   { "DumpBytecode", 0x00000002 },
   { "Profile", 0x00000004 },
   { "TopTips", 0x00000008 },
   { "Tips", 0x00000010 },
   { "AllTips", 0x00000020 },
   { "DisableJit", 0x00000040 },
   { "TraceCfg", 0x00000080 },
   { "TraceTypes", 0x00000100 },
   { "TraceTokens", 0x00000200 },
   { "TraceExpect", 0x00000400 },
   { "TraceBoundary", 0x00000800 },
   { "TraceOperators", 0x00001000 },
   { "TraceRegisters", 0x00002000 },
   { "TraceAssignments", 0x00004000 },
   { "TraceValueCategory", 0x00008000 },
   { "Trace", 0x0000ff80 },
   { nullptr, 0 }
};

static ERR TIRI_NewPlacement(extTiri *Self) {
   new (Self) extTiri(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR TIRI_FreePlacement(extTiri *Self) {
   Self->~extTiri();
   return ERR::Okay;
}

static const struct ActionArray clTiriActions[] = {
   { AC::Activate, TIRI_Activate },
   { AC::DataFeed, TIRI_DataFeed },
   { AC::FreePlacement, TIRI_FreePlacement },
   { AC::Init, TIRI_Init },
   { AC::NewChild, TIRI_NewChild },
   { AC::NewPlacement, TIRI_NewPlacement },
   { AC::Query, TIRI_Query },
   { AC::SaveToObject, TIRI_SaveToObject },
   { AC::NIL, nullptr }
};

