// Auto-generated by idl-c.tiri

static ERR OFFSETFX_New(extOffsetFX *Self) {
   new (Self) extOffsetFX(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR OFFSETFX_Free(extOffsetFX *Self) {
   Self->~extOffsetFX();
   return ERR::Okay;
}

static const struct ActionArray clOffsetFXActions[] = {
   { AC::Draw, OFFSETFX_Draw },
   { AC::Free, OFFSETFX_Free },
   { AC::New, OFFSETFX_New },
   { AC::NIL, nullptr }
};

