// Auto-generated by idl-c.tiri

static const struct FieldDef clImageFXVSM[] = {
   { "Auto", 0x00000000 },
   { "Neighbour", 0x00000001 },
   { "Bilinear", 0x00000002 },
   { "Bicubic", 0x00000003 },
   { "Spline16", 0x00000004 },
   { "Kaiser", 0x00000005 },
   { "Quadric", 0x00000006 },
   { "Gaussian", 0x00000007 },
   { "Bessel", 0x00000008 },
   { "Mitchell", 0x00000009 },
   { "Sinc", 0x0000000a },
   { "Lanczos", 0x0000000b },
   { "Blackman", 0x0000000c },
   { nullptr, 0 }
};

static ERR IMAGEFX_NewPlacement(extImageFX *Self) {
   new (Self) extImageFX(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR IMAGEFX_FreePlacement(extImageFX *Self) {
   Self->~extImageFX();
   return ERR::Okay;
}

static const struct ActionArray clImageFXActions[] = {
   { AC::Draw, IMAGEFX_Draw },
   { AC::FreePlacement, IMAGEFX_FreePlacement },
   { AC::Init, IMAGEFX_Init },
   { AC::NewChild, IMAGEFX_NewChild },
   { AC::NewPlacement, IMAGEFX_NewPlacement },
   { AC::NIL, nullptr }
};

