// Auto-generated by idl-c.tiri

static ERR SOURCEFX_New(extSourceFX *Self) {
   new (Self) extSourceFX(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR SOURCEFX_Free(extSourceFX *Self) {
   Self->~extSourceFX();
   return ERR::Okay;
}

static const struct ActionArray clSourceFXActions[] = {
   { AC::Draw, SOURCEFX_Draw },
   { AC::Free, SOURCEFX_Free },
   { AC::Init, SOURCEFX_Init },
   { AC::New, SOURCEFX_New },
   { AC::NIL, nullptr }
};

