// Auto-generated by idl-c.tiri

static ERR CONVOLVEFX_NewPlacement(extConvolveFX *Self) {
   new (Self) extConvolveFX;
   return ERR::Okay;
}

static const struct ActionArray clConvolveFXActions[] = {
   { AC::Draw, CONVOLVEFX_Draw },
   { AC::Free, CONVOLVEFX_Free },
   { AC::Init, CONVOLVEFX_Init },
   { AC::NewPlacement, CONVOLVEFX_NewPlacement },
   { AC::NIL, nullptr }
};

