// Auto-generated by idl-c.tiri

static const struct FieldDef clCompositeFXOP[] = {
   { "Over", 0x00000000 },
   { "In", 0x00000001 },
   { "Out", 0x00000002 },
   { "Atop", 0x00000003 },
   { "Xor", 0x00000004 },
   { "Arithmetic", 0x00000005 },
   { "Screen", 0x00000006 },
   { "Multiply", 0x00000007 },
   { "Lighten", 0x00000008 },
   { "Darken", 0x00000009 },
   { "InvertRGB", 0x0000000a },
   { "Invert", 0x0000000b },
   { "Contrast", 0x0000000c },
   { "Dodge", 0x0000000d },
   { "Burn", 0x0000000e },
   { "HardLight", 0x0000000f },
   { "SoftLight", 0x00000010 },
   { "Difference", 0x00000011 },
   { "Exclusion", 0x00000012 },
   { "Plus", 0x00000013 },
   { "Minus", 0x00000014 },
   { "Subtract", 0x00000014 },
   { "Overlay", 0x00000015 },
   { nullptr, 0 }
};

static ERR COMPOSITEFX_New(extCompositeFX *Self) {
   new (Self) extCompositeFX(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR COMPOSITEFX_Free(extCompositeFX *Self) {
   Self->~extCompositeFX();
   return ERR::Okay;
}

static const struct ActionArray clCompositeFXActions[] = {
   { AC::Draw, COMPOSITEFX_Draw },
   { AC::Free, COMPOSITEFX_Free },
   { AC::Init, COMPOSITEFX_Init },
   { AC::New, COMPOSITEFX_New },
   { AC::NIL, nullptr }
};

