// Auto-generated by idl-c.tiri

static ERR BLURFX_New(extBlurFX *Self) {
   new (Self) extBlurFX(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR BLURFX_Free(extBlurFX *Self) {
   Self->~extBlurFX();
   return ERR::Okay;
}

static const struct ActionArray clBlurFXActions[] = {
   { AC::Draw, BLURFX_Draw },
   { AC::Free, BLURFX_Free },
   { AC::New, BLURFX_New },
   { AC::NIL, nullptr }
};

