// Auto-generated by idl-c.tiri

static ERR FLOODFX_New(extFloodFX *Self) {
   new (Self) extFloodFX(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR FLOODFX_Free(extFloodFX *Self) {
   Self->~extFloodFX();
   return ERR::Okay;
}

static const struct ActionArray clFloodFXActions[] = {
   { AC::Draw, FLOODFX_Draw },
   { AC::Free, FLOODFX_Free },
   { AC::New, FLOODFX_New },
   { AC::NIL, nullptr }
};

