// Auto-generated by idl-c.tiri

static ERR MORPHOLOGYFX_NewPlacement(extMorphologyFX *Self) {
   new (Self) extMorphologyFX;
   return ERR::Okay;
}

static const struct ActionArray clMorphologyFXActions[] = {
   { AC::Draw, MORPHOLOGYFX_Draw },
   { AC::NewObject, MORPHOLOGYFX_NewObject },
   { AC::NewPlacement, MORPHOLOGYFX_NewPlacement },
   { AC::NIL, nullptr }
};

