// Auto-generated by idl-c.tiri

static const struct FieldDef clFilterEffectSourceType[] = {
   { "Ignore", 0x00000000 },
   { "None", 0x00000000 },
   { "Graphic", 0x00000001 },
   { "Alpha", 0x00000002 },
   { "Bkgd", 0x00000003 },
   { "BkgdAlpha", 0x00000004 },
   { "Fill", 0x00000005 },
   { "Stroke", 0x00000006 },
   { "Reference", 0x00000007 },
   { "Previous", 0x00000008 },
   { nullptr, 0 }
};

static const struct FieldDef clFilterEffectMixType[] = {
   { "Ignore", 0x00000000 },
   { "None", 0x00000000 },
   { "Graphic", 0x00000001 },
   { "Alpha", 0x00000002 },
   { "Bkgd", 0x00000003 },
   { "BkgdAlpha", 0x00000004 },
   { "Fill", 0x00000005 },
   { "Stroke", 0x00000006 },
   { "Reference", 0x00000007 },
   { "Previous", 0x00000008 },
   { nullptr, 0 }
};

static const struct FieldDef clFilterEffectVSF[] = {
   { "Ignore", 0x00000000 },
   { "None", 0x00000000 },
   { "Graphic", 0x00000001 },
   { "Alpha", 0x00000002 },
   { "Bkgd", 0x00000003 },
   { "BkgdAlpha", 0x00000004 },
   { "Fill", 0x00000005 },
   { "Stroke", 0x00000006 },
   { "Reference", 0x00000007 },
   { "Previous", 0x00000008 },
   { nullptr, 0 }
};

static ERR FILTEREFFECT_New(extFilterEffect *Self) {
   new (Self) extFilterEffect(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR FILTEREFFECT_Free(extFilterEffect *Self) {
   Self->~extFilterEffect();
   return ERR::Okay;
}

static const struct ActionArray clFilterEffectActions[] = {
   { AC::Free, FILTEREFFECT_Free },
   { AC::Init, FILTEREFFECT_Init },
   { AC::MoveToBack, FILTEREFFECT_MoveToBack },
   { AC::MoveToFront, FILTEREFFECT_MoveToFront },
   { AC::New, FILTEREFFECT_New },
   { AC::NewOwner, FILTEREFFECT_NewOwner },
   { AC::NIL, nullptr }
};

