// Auto-generated by idl-c.tiri

static ERR BLURFX_NewPlacement(extBlurFX *Self) {
   new (Self) extBlurFX;
   return ERR::Okay;
}

static const struct ActionArray clBlurFXActions[] = {
   { AC::Draw, BLURFX_Draw },
   { AC::NewPlacement, BLURFX_NewPlacement },
   { AC::NIL, nullptr }
};

