// Auto-generated by idl-c.tiri

static ERR WAVEFUNCTIONFX_New(extWaveFunctionFX *Self) {
   new (Self) extWaveFunctionFX(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR WAVEFUNCTIONFX_Free(extWaveFunctionFX *Self) {
   Self->~extWaveFunctionFX();
   return ERR::Okay;
}

static const struct ActionArray clWaveFunctionFXActions[] = {
   { AC::Draw, WAVEFUNCTIONFX_Draw },
   { AC::Free, WAVEFUNCTIONFX_Free },
   { AC::New, WAVEFUNCTIONFX_New },
   { AC::NIL, nullptr }
};

