// Auto-generated by idl-c.tiri

static ERR TURBULENCEFX_NewPlacement(extTurbulenceFX *Self) {
   new (Self) extTurbulenceFX;
   return ERR::Okay;
}

static const struct ActionArray clTurbulenceFXActions[] = {
   { AC::Draw, TURBULENCEFX_Draw },
   { AC::Free, TURBULENCEFX_Free },
   { AC::Init, TURBULENCEFX_Init },
   { AC::NewObject, TURBULENCEFX_NewObject },
   { AC::NewPlacement, TURBULENCEFX_NewPlacement },
   { AC::NIL, nullptr }
};

