// Auto-generated by idl-c.tiri

static ERR DISPLACEMENTFX_NewPlacement(extDisplacementFX *Self) {
   new (Self) extDisplacementFX;
   return ERR::Okay;
}

static const struct ActionArray clDisplacementFXActions[] = {
   { AC::Draw, DISPLACEMENTFX_Draw },
   { AC::NewObject, DISPLACEMENTFX_NewObject },
   { AC::NewPlacement, DISPLACEMENTFX_NewPlacement },
   { AC::NIL, nullptr }
};

