// Auto-generated by idl-c.tiri

static const struct FieldDef clColourFXCM[] = {
   { "None", 0x00000000 },
   { "Matrix", 0x00000001 },
   { "Saturate", 0x00000002 },
   { "HueRotate", 0x00000003 },
   { "LuminanceAlpha", 0x00000004 },
   { "Contrast", 0x00000005 },
   { "Brightness", 0x00000006 },
   { "Hue", 0x00000007 },
   { "Desaturate", 0x00000008 },
   { "Colourise", 0x00000009 },
   { nullptr, 0 }
};

static ERR COLOURFX_NewPlacement(extColourFX *Self) {
   new (Self) extColourFX;
   return ERR::Okay;
}

static ERR COLOURFX_FreePlacement(extColourFX *Self) {
   Self->~extColourFX();
   return ERR::Okay;
}

static const struct ActionArray clColourFXActions[] = {
   { AC::Draw, COLOURFX_Draw },
   { AC::FreePlacement, COLOURFX_FreePlacement },
   { AC::Init, COLOURFX_Init },
   { AC::NewPlacement, COLOURFX_NewPlacement },
   { AC::NIL, nullptr }
};

