// Auto-generated by idl-c.tiri

static const struct FieldDef clConvolveFXEM[] = {
   { "Duplicate", 0x00000001 },
   { "Wrap", 0x00000002 },
   { "None", 0x00000003 },
   { nullptr, 0 }
};

static ERR CONVOLVEFX_NewPlacement(extConvolveFX *Self) {
   new (Self) extConvolveFX(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR CONVOLVEFX_FreePlacement(extConvolveFX *Self) {
   Self->~extConvolveFX();
   return ERR::Okay;
}

static const struct ActionArray clConvolveFXActions[] = {
   { AC::Draw, CONVOLVEFX_Draw },
   { AC::FreePlacement, CONVOLVEFX_FreePlacement },
   { AC::Init, CONVOLVEFX_Init },
   { AC::NewPlacement, CONVOLVEFX_NewPlacement },
   { AC::NIL, nullptr }
};

