// Auto-generated by idl-c.tiri

static const struct FieldDef clMorphologyFXMOP[] = {
   { "Erode", 0x00000000 },
   { "Dilate", 0x00000001 },
   { nullptr, 0 }
};

static ERR MORPHOLOGYFX_NewPlacement(extMorphologyFX *Self) {
   new (Self) extMorphologyFX(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR MORPHOLOGYFX_FreePlacement(extMorphologyFX *Self) {
   Self->~extMorphologyFX();
   return ERR::Okay;
}

static const struct ActionArray clMorphologyFXActions[] = {
   { AC::Draw, MORPHOLOGYFX_Draw },
   { AC::FreePlacement, MORPHOLOGYFX_FreePlacement },
   { AC::NewPlacement, MORPHOLOGYFX_NewPlacement },
   { AC::NIL, nullptr }
};

