// Auto-generated by idl-c.tiri

static const struct FieldDef clTurbulenceFXTB[] = {
   { "Turbulence", 0x00000000 },
   { "Noise", 0x00000001 },
   { nullptr, 0 }
};

static ERR TURBULENCEFX_New(extTurbulenceFX *Self) {
   new (Self) extTurbulenceFX(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR TURBULENCEFX_Free(extTurbulenceFX *Self) {
   Self->~extTurbulenceFX();
   return ERR::Okay;
}

static const struct ActionArray clTurbulenceFXActions[] = {
   { AC::Draw, TURBULENCEFX_Draw },
   { AC::Free, TURBULENCEFX_Free },
   { AC::Init, TURBULENCEFX_Init },
   { AC::New, TURBULENCEFX_New },
   { AC::NIL, nullptr }
};

