// Auto-generated by idl-c.tiri

static ERR COMPOSITEFX_NewPlacement(extCompositeFX *Self) {
   new (Self) extCompositeFX;
   return ERR::Okay;
}

static ERR COMPOSITEFX_FreePlacement(extCompositeFX *Self) {
   Self->~extCompositeFX();
   return ERR::Okay;
}

static const struct ActionArray clCompositeFXActions[] = {
   { AC::Draw, COMPOSITEFX_Draw },
   { AC::FreePlacement, COMPOSITEFX_FreePlacement },
   { AC::Init, COMPOSITEFX_Init },
   { AC::NewObject, COMPOSITEFX_NewObject },
   { AC::NewPlacement, COMPOSITEFX_NewPlacement },
   { AC::NIL, nullptr }
};

