// Auto-generated by idl-c.tiri

static const struct FieldDef clDisplacementFXCMP[] = {
   { "All", (int)0xffffffff },
   { "Red", 0x00000000 },
   { "Green", 0x00000001 },
   { "Blue", 0x00000002 },
   { "Alpha", 0x00000003 },
   { nullptr, 0 }
};

static ERR DISPLACEMENTFX_NewPlacement(extDisplacementFX *Self) {
   new (Self) extDisplacementFX;
   return ERR::Okay;
}

static ERR DISPLACEMENTFX_FreePlacement(extDisplacementFX *Self) {
   Self->~extDisplacementFX();
   return ERR::Okay;
}

static const struct ActionArray clDisplacementFXActions[] = {
   { AC::Draw, DISPLACEMENTFX_Draw },
   { AC::FreePlacement, DISPLACEMENTFX_FreePlacement },
   { AC::NewPlacement, DISPLACEMENTFX_NewPlacement },
   { AC::NIL, nullptr }
};

