// Auto-generated by idl-c.tiri

static ERR OFFSETFX_NewPlacement(extOffsetFX *Self) {
   new (Self) extOffsetFX;
   return ERR::Okay;
}

static const struct ActionArray clOffsetFXActions[] = {
   { AC::Draw, OFFSETFX_Draw },
   { AC::NewPlacement, OFFSETFX_NewPlacement },
   { AC::NIL, nullptr }
};

