// Auto-generated by idl-c.tiri

static ERR COLOURFX_NewPlacement(extColourFX *Self) {
   new (Self) extColourFX;
   return ERR::Okay;
}

static const struct ActionArray clColourFXActions[] = {
   { AC::Draw, COLOURFX_Draw },
   { AC::Free, COLOURFX_Free },
   { AC::Init, COLOURFX_Init },
   { AC::NewObject, COLOURFX_NewObject },
   { AC::NewPlacement, COLOURFX_NewPlacement },
   { AC::NIL, nullptr }
};

