// Auto-generated by idl-c.tiri

static const struct FieldDef clLightingFXLT[] = {
   { "Diffuse", 0x00000000 },
   { "Specular", 0x00000001 },
   { nullptr, 0 }
};

FDEF maSetDistantLight[] = { { "Azimuth", FD_DOUBLE }, { "Elevation", FD_DOUBLE }, { 0, 0 } };
FDEF maSetPointLight[] = { { "X", FD_DOUBLE }, { "Y", FD_DOUBLE }, { "Z", FD_DOUBLE }, { 0, 0 } };
FDEF maSetSpotLight[] = { { "X", FD_DOUBLE }, { "Y", FD_DOUBLE }, { "Z", FD_DOUBLE }, { "PX", FD_DOUBLE }, { "PY", FD_DOUBLE }, { "PZ", FD_DOUBLE }, { "Exponent", FD_DOUBLE }, { "ConeAngle", FD_DOUBLE }, { 0, 0 } };

static const struct MethodEntry clLightingFXMethods[] = {
   { AC(-20), (APTR)LIGHTINGFX_SetDistantLight, "SetDistantLight", maSetDistantLight, sizeof(struct lt::SetDistantLight) },
   { AC(-22), (APTR)LIGHTINGFX_SetPointLight, "SetPointLight", maSetPointLight, sizeof(struct lt::SetPointLight) },
   { AC(-21), (APTR)LIGHTINGFX_SetSpotLight, "SetSpotLight", maSetSpotLight, sizeof(struct lt::SetSpotLight) },
   { AC::NIL, 0, 0, 0, 0 }
};

static ERR LIGHTINGFX_New(extLightingFX *Self) {
   new (Self) extLightingFX(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR LIGHTINGFX_Free(extLightingFX *Self) {
   Self->~extLightingFX();
   return ERR::Okay;
}

static const struct ActionArray clLightingFXActions[] = {
   { AC::Draw, LIGHTINGFX_Draw },
   { AC::Free, LIGHTINGFX_Free },
   { AC::New, LIGHTINGFX_New },
   { AC::NIL, nullptr }
};

