// Auto-generated by idl-c.tiri

static const struct FieldDef clTurbulenceFXTB[] = {
   { "Turbulence", 0x00000000 },
   { "Noise", 0x00000001 },
   { nullptr, 0 }
};

static ERR TURBULENCEFX_NewPlacement(extTurbulenceFX *Self) {
   new (Self) extTurbulenceFX;
   return ERR::Okay;
}

static ERR TURBULENCEFX_FreePlacement(extTurbulenceFX *Self) {
   Self->~extTurbulenceFX();
   return ERR::Okay;
}

static const struct ActionArray clTurbulenceFXActions[] = {
   { AC::Draw, TURBULENCEFX_Draw },
   { AC::FreePlacement, TURBULENCEFX_FreePlacement },
   { AC::Init, TURBULENCEFX_Init },
   { AC::NewPlacement, TURBULENCEFX_NewPlacement },
   { AC::NIL, nullptr }
};

