// Auto-generated by idl-c.tiri

static const struct FieldDef clVectorFilterUnits[] = {
   { "Undefined", 0x00000000 },
   { "BoundingBox", 0x00000001 },
   { "Userspace", 0x00000002 },
   { nullptr, 0 }
};

static const struct FieldDef clVectorFilterPrimitiveUnits[] = {
   { "Undefined", 0x00000000 },
   { "BoundingBox", 0x00000001 },
   { "Userspace", 0x00000002 },
   { nullptr, 0 }
};

static const struct FieldDef clVectorFilterColourSpace[] = {
   { "Inherit", 0x00000000 },
   { "SRGB", 0x00000001 },
   { "LinearRGB", 0x00000002 },
   { nullptr, 0 }
};

static const struct FieldDef clVectorFilterAspectRatio[] = {
   { "Meet", 0x00000000 },
   { "None", 0x00000001 },
   { nullptr, 0 }
};

static ERR VECTORFILTER_NewPlacement(extVectorFilter *Self) {
   new (Self) extVectorFilter;
   return ERR::Okay;
}

static ERR VECTORFILTER_FreePlacement(extVectorFilter *Self) {
   Self->~extVectorFilter();
   return ERR::Okay;
}

static const struct ActionArray clVectorFilterActions[] = {
   { AC::Clear, VECTORFILTER_Clear },
   { AC::FreePlacement, VECTORFILTER_FreePlacement },
   { AC::Init, VECTORFILTER_Init },
   { AC::NewChild, VECTORFILTER_NewChild },
   { AC::NewOwner, VECTORFILTER_NewOwner },
   { AC::NewPlacement, VECTORFILTER_NewPlacement },
   { AC::NIL, nullptr }
};

