// Auto-generated by idl-c.tiri

static ERR FLOODFX_NewPlacement(extFloodFX *Self) {
   new (Self) extFloodFX;
   return ERR::Okay;
}

static const struct ActionArray clFloodFXActions[] = {
   { AC::Draw, FLOODFX_Draw },
   { AC::NewObject, FLOODFX_NewObject },
   { AC::NewPlacement, FLOODFX_NewPlacement },
   { AC::NIL, nullptr }
};

