// Auto-generated by idl-c.tiri

static ERR WAVEFUNCTIONFX_NewPlacement(extWaveFunctionFX *Self) {
   new (Self) extWaveFunctionFX;
   return ERR::Okay;
}

static ERR WAVEFUNCTIONFX_FreePlacement(extWaveFunctionFX *Self) {
   Self->~extWaveFunctionFX();
   return ERR::Okay;
}

static const struct ActionArray clWaveFunctionFXActions[] = {
   { AC::Draw, WAVEFUNCTIONFX_Draw },
   { AC::Free, WAVEFUNCTIONFX_Free },
   { AC::FreePlacement, WAVEFUNCTIONFX_FreePlacement },
   { AC::Init, WAVEFUNCTIONFX_Init },
   { AC::NewObject, WAVEFUNCTIONFX_NewObject },
   { AC::NewPlacement, WAVEFUNCTIONFX_NewPlacement },
   { AC::NIL, nullptr }
};

