// Auto-generated by idl-c.tiri

static ERR MERGEFX_New(extMergeFX *Self) {
   new (Self) extMergeFX(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR MERGEFX_Free(extMergeFX *Self) {
   Self->~extMergeFX();
   return ERR::Okay;
}

static const struct ActionArray clMergeFXActions[] = {
   { AC::Draw, MERGEFX_Draw },
   { AC::Free, MERGEFX_Free },
   { AC::New, MERGEFX_New },
   { AC::NIL, nullptr }
};

