// Auto-generated by idl-c.tiri

static ERR MP3_NewPlacement(objMP3 *Self) {
   new (Self) objMP3;
   return ERR::Okay;
}

static ERR MP3_FreePlacement(objMP3 *Self) {
   Self->~objMP3();
   return ERR::Okay;
}

static const struct ActionArray clMP3Actions[] = {
   { AC::FreePlacement, MP3_FreePlacement },
   { AC::Init, MP3_Init },
   { AC::NewPlacement, MP3_NewPlacement },
   { AC::Read, MP3_Read },
   { AC::Seek, MP3_Seek },
   { AC::NIL, nullptr }
};

