// Auto-generated by idl-c.tiri

static ERR MP3_New(objMP3 *Self) {
   new (Self) objMP3(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR MP3_Free(objMP3 *Self) {
   Self->~objMP3();
   return ERR::Okay;
}

static const struct ActionArray clMP3Actions[] = {
   { AC::Free, MP3_Free },
   { AC::Init, MP3_Init },
   { AC::New, MP3_New },
   { AC::Read, MP3_Read },
   { AC::Seek, MP3_Seek },
   { AC::NIL, nullptr }
};

