// Auto-generated by idl-c.tiri

static ERR NETCLIENT_NewPlacement(objNetClient *Self) {
   new (Self) objNetClient;
   return ERR::Okay;
}

static const struct ActionArray clNetClientActions[] = {
   { AC::Free, NETCLIENT_Free },
   { AC::Init, NETCLIENT_Init },
   { AC::NewPlacement, NETCLIENT_NewPlacement },
   { AC::NIL, nullptr }
};

