// Auto-generated by idl-c.tiri

static ERR NETCLIENT_NewPlacement(objNetClient *Self) {
   new (Self) objNetClient(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR NETCLIENT_FreePlacement(objNetClient *Self) {
   Self->~objNetClient();
   return ERR::Okay;
}

static const struct ActionArray clNetClientActions[] = {
   { AC::FreePlacement, NETCLIENT_FreePlacement },
   { AC::Init, NETCLIENT_Init },
   { AC::NewPlacement, NETCLIENT_NewPlacement },
   { AC::NIL, nullptr }
};

