// Auto-generated by idl-c.tiri

static ERR NETCLIENT_New(objNetClient *Self) {
   new (Self) objNetClient(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR NETCLIENT_Free(objNetClient *Self) {
   Self->~objNetClient();
   return ERR::Okay;
}

static const struct ActionArray clNetClientActions[] = {
   { AC::Free, NETCLIENT_Free },
   { AC::Init, NETCLIENT_Init },
   { AC::New, NETCLIENT_New },
   { AC::NIL, nullptr }
};

