// Auto-generated by idl-c.tiri

static const struct FieldDef clSVGFlags[] = {
   { "Autoscale", 0x00000001 },
   { "Alpha", 0x00000002 },
   { "EnforceTracking", 0x00000004 },
   { nullptr, 0 }
};

FDEF maRender[] = { { "Bitmap", FD_OBJECTPTR }, { "X", FD_INT }, { "Y", FD_INT }, { "Width", FD_INT }, { "Height", FD_INT }, { 0, 0 } };
FDEF maParseSymbol[] = { { "ID", FDF_CPPSTRING }, { "Viewport", FD_OBJECTPTR }, { 0, 0 } };

static const struct MethodEntry clSVGMethods[] = {
   { AC(-1), (APTR)SVG_Render, "Render", maRender, sizeof(struct svg::Render) },
   { AC(-2), (APTR)SVG_ParseSymbol, "ParseSymbol", maParseSymbol, sizeof(struct svg::ParseSymbol) },
   { AC::NIL, 0, 0, 0, 0 }
};

static ERR SVG_NewPlacement(extSVG *Self) {
   new (Self) extSVG(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR SVG_FreePlacement(extSVG *Self) {
   Self->~extSVG();
   return ERR::Okay;
}

static const struct ActionArray clSVGActions[] = {
   { AC::Activate, SVG_Activate },
   { AC::DataFeed, SVG_DataFeed },
   { AC::Deactivate, SVG_Deactivate },
   { AC::FreePlacement, SVG_FreePlacement },
   { AC::Init, SVG_Init },
   { AC::NewPlacement, SVG_NewPlacement },
   { AC::SaveImage, SVG_SaveImage },
   { AC::SaveToObject, SVG_SaveToObject },
   { AC::NIL, nullptr }
};

