// Auto-generated by idl-c.tiri

FDEF maFind[] = { { "Port", FD_INT }, { "Enabled", FD_INT }, { 0, 0 } };

static const struct MethodEntry clProxyMethods[] = {
   { AC(-1), (APTR)PROXY_DeleteRecord, "DeleteRecord", 0, 0 },
   { AC(-2), (APTR)PROXY_Find, "Find", maFind, sizeof(struct prx::Find) },
   { AC(-3), (APTR)PROXY_FindNext, "FindNext", 0, 0 },
   { AC::NIL, 0, 0, 0, 0 }
};

static ERR PROXY_NewPlacement(extProxy *Self) {
   new (Self) extProxy(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR PROXY_FreePlacement(extProxy *Self) {
   Self->~extProxy();
   return ERR::Okay;
}

static const struct ActionArray clProxyActions[] = {
   { AC::Disable, PROXY_Disable },
   { AC::Enable, PROXY_Enable },
   { AC::FreePlacement, PROXY_FreePlacement },
   { AC::NewPlacement, PROXY_NewPlacement },
   { AC::SaveSettings, PROXY_SaveSettings },
   { AC::NIL, nullptr }
};

