// Auto-generated by idl-c.tiri

static const struct FieldDef clNetLookupFlags[] = {
   { "NoCache", 0x00000001 },
   { nullptr, 0 }
};

FDEF maResolveName[] = { { "HostName", FDF_CPPSTRING }, { 0, 0 } };
FDEF maResolveAddress[] = { { "Address", FDF_CPPSTRING }, { 0, 0 } };
FDEF maBlockingResolveName[] = { { "HostName", FDF_CPPSTRING }, { 0, 0 } };
FDEF maBlockingResolveAddress[] = { { "Address", FDF_CPPSTRING }, { 0, 0 } };

static const struct MethodEntry clNetLookupMethods[] = {
   { AC(-1), (APTR)NETLOOKUP_ResolveName, "ResolveName", maResolveName, sizeof(struct nl::ResolveName) },
   { AC(-2), (APTR)NETLOOKUP_ResolveAddress, "ResolveAddress", maResolveAddress, sizeof(struct nl::ResolveAddress) },
   { AC(-3), (APTR)NETLOOKUP_BlockingResolveName, "BlockingResolveName", maBlockingResolveName, sizeof(struct nl::BlockingResolveName) },
   { AC(-4), (APTR)NETLOOKUP_BlockingResolveAddress, "BlockingResolveAddress", maBlockingResolveAddress, sizeof(struct nl::BlockingResolveAddress) },
   { AC::NIL, 0, 0, 0, 0 }
};

static ERR NETLOOKUP_NewPlacement(extNetLookup *Self) {
   new (Self) extNetLookup(Self->Class, Self->UID);
   return ERR::Okay;
}

static ERR NETLOOKUP_FreePlacement(extNetLookup *Self) {
   Self->~extNetLookup();
   return ERR::Okay;
}

static const struct ActionArray clNetLookupActions[] = {
   { AC::FreePlacement, NETLOOKUP_FreePlacement },
   { AC::FreeWarning, NETLOOKUP_FreeWarning },
   { AC::NewPlacement, NETLOOKUP_NewPlacement },
   { AC::NIL, nullptr }
};

